/**
 * IFTA Quarterly Report — Professional PDF Export
 *
 * Uses jsPDF + jspdf-autotable (same stack as the rest of TruckerBook exports).
 * Generates a CPA-ready document with header, state breakdown table,
 * totals summary, and legal disclaimer.
 */

const QUARTER_MONTHS = {
  1: { en: 'January 1 \u2014 March 31',   ru: '1 \u044f\u043d\u0432\u0430\u0440\u044f \u2014 31 \u043c\u0430\u0440\u0442\u0430',   uk: '1 \u0441\u0456\u0447\u043d\u044f \u2014 31 \u0431\u0435\u0440\u0435\u0437\u043d\u044f',   es: '1 de enero \u2014 31 de marzo',   de: '1. Januar \u2014 31. M\u00e4rz',   fr: '1 janvier \u2014 31 mars',   tr: '1 Ocak \u2014 31 Mart',   pl: '1 stycznia \u2014 31 marca' },
  2: { en: 'April 1 \u2014 June 30',      ru: '1 \u0430\u043f\u0440\u0435\u043b\u044f \u2014 30 \u0438\u044e\u043d\u044f',      uk: '1 \u043a\u0432\u0456\u0442\u043d\u044f \u2014 30 \u0447\u0435\u0440\u0432\u043d\u044f',    es: '1 de abril \u2014 30 de junio',  de: '1. April \u2014 30. Juni',    fr: '1 avril \u2014 30 juin',    tr: '1 Nisan \u2014 30 Haziran',  pl: '1 kwietnia \u2014 30 czerwca' },
  3: { en: 'July 1 \u2014 September 30',  ru: '1 \u0438\u044e\u043b\u044f \u2014 30 \u0441\u0435\u043d\u0442\u044f\u0431\u0440\u044f',  uk: '1 \u043b\u0438\u043f\u043d\u044f \u2014 30 \u0432\u0435\u0440\u0435\u0441\u043d\u044f',    es: '1 de julio \u2014 30 de septiembre', de: '1. Juli \u2014 30. September', fr: '1 juillet \u2014 30 septembre', tr: '1 Temmuz \u2014 30 Eyl\u00fcl', pl: '1 lipca \u2014 30 wrze\u015bnia' },
  4: { en: 'October 1 \u2014 December 31', ru: '1 \u043e\u043a\u0442\u044f\u0431\u0440\u044f \u2014 31 \u0434\u0435\u043a\u0430\u0431\u0440\u044f', uk: '1 \u0436\u043e\u0432\u0442\u043d\u044f \u2014 31 \u0433\u0440\u0443\u0434\u043d\u044f',   es: '1 de octubre \u2014 31 de diciembre', de: '1. Oktober \u2014 31. Dezember', fr: '1 octobre \u2014 31 d\u00e9cembre', tr: '1 Ekim \u2014 31 Aral\u0131k', pl: '1 pa\u017adziernika \u2014 31 grudnia' },
}

// Localized labels used in the PDF (table columns are always English — IFTA standard)
const PDF_LABELS = {
  en: {
    title: 'TruckerBook \u2014 IFTA Quarterly Report',
    period: 'Period',
    vehicle: 'Vehicle',
    allVehicles: 'All Vehicles (Fleet Report)',
    generated: 'Generated',
    status: 'Status',
    draft: 'DRAFT',
    final: 'FINAL',
    totalMiles: 'Total Miles Driven',
    totalGallons: 'Total Gallons Purchased',
    fleetMpg: 'Fleet Average MPG',
    totalTax: 'Total Tax Liability',
    totalSurcharge: 'Total Surcharges',
    totalCredits: 'Total Credits (fuel tax paid at pump)',
    netBalance: 'NET BALANCE',
    oweNote: 'Amount owed to IFTA',
    creditNote: 'Credit / refund due',
    credit: '(credit)',
    total: 'TOTAL',
    disclaimer: 'This report is generated by TruckerBook for informational purposes only. It is NOT a substitute for professional tax preparation. Verify all figures with a licensed CPA or EA before filing. Tax rates sourced from IFTA Inc. Tax Rate Matrix.',
    footer: 'Generated by TruckerBook | truckerbook-app.vercel.app',
    page: 'Page',
  },
  ru: {
    title: 'TruckerBook \u2014 \u041a\u0432\u0430\u0440\u0442\u0430\u043b\u044c\u043d\u044b\u0439 \u043e\u0442\u0447\u0451\u0442 IFTA',
    period: '\u041f\u0435\u0440\u0438\u043e\u0434',
    vehicle: '\u0422\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442',
    allVehicles: '\u0412\u0441\u0435 \u0422\u0421 (\u043e\u0442\u0447\u0451\u0442 \u043f\u043e \u043f\u0430\u0440\u043a\u0443)',
    generated: '\u0421\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d',
    status: '\u0421\u0442\u0430\u0442\u0443\u0441',
    draft: '\u0427\u0415\u0420\u041d\u041e\u0412\u0418\u041a',
    final: '\u0424\u0418\u041d\u0410\u041b',
    totalMiles: '\u0412\u0441\u0435\u0433\u043e \u043c\u0438\u043b\u044c',
    totalGallons: '\u0412\u0441\u0435\u0433\u043e \u0433\u0430\u043b\u043b\u043e\u043d\u043e\u0432 \u043a\u0443\u043f\u043b\u0435\u043d\u043e',
    fleetMpg: '\u0421\u0440\u0435\u0434\u043d\u0438\u0439 MPG \u043f\u043e \u043f\u0430\u0440\u043a\u0443',
    totalTax: '\u041d\u0430\u043b\u043e\u0433\u043e\u0432\u044b\u0435 \u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430',
    totalSurcharge: '\u0414\u043e\u043f\u043b\u0430\u0442\u044b',
    totalCredits: '\u041a\u0440\u0435\u0434\u0438\u0442\u044b (\u043d\u0430\u043b\u043e\u0433 \u043e\u043f\u043b\u0430\u0447\u0435\u043d \u043d\u0430 \u0410\u0417\u0421)',
    netBalance: '\u0418\u0422\u041e\u0413\u041e',
    oweNote: '\u0421\u0443\u043c\u043c\u0430 \u043a \u0443\u043f\u043b\u0430\u0442\u0435 IFTA',
    creditNote: '\u041a\u0440\u0435\u0434\u0438\u0442 / \u0432\u043e\u0437\u0432\u0440\u0430\u0442',
    credit: '(\u043a\u0440\u0435\u0434\u0438\u0442)',
    total: '\u0418\u0422\u041e\u0413\u041e',
    disclaimer: '\u042d\u0442\u043e\u0442 \u043e\u0442\u0447\u0451\u0442 \u0441\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d TruckerBook \u0438\u0441\u043a\u043b\u044e\u0447\u0438\u0442\u0435\u043b\u044c\u043d\u043e \u0432 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0445 \u0446\u0435\u043b\u044f\u0445. \u041e\u043d \u041d\u0415 \u0437\u0430\u043c\u0435\u043d\u044f\u0435\u0442 \u043f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u0443\u044e \u043d\u0430\u043b\u043e\u0433\u043e\u0432\u0443\u044e \u043f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0443. \u041f\u0435\u0440\u0435\u0434 \u043f\u043e\u0434\u0430\u0447\u0435\u0439 \u043f\u0440\u043e\u0432\u0435\u0440\u044c\u0442\u0435 \u0432\u0441\u0435 \u0446\u0438\u0444\u0440\u044b \u0441 \u043b\u0438\u0446\u0435\u043d\u0437\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u043c CPA \u0438\u043b\u0438 EA. \u0421\u0442\u0430\u0432\u043a\u0438 \u0432\u0437\u044f\u0442\u044b \u0438\u0437 IFTA Inc. Tax Rate Matrix.',
    footer: '\u0421\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u043e TruckerBook | truckerbook-app.vercel.app',
    page: '\u0421\u0442\u0440.',
  },
  uk: {
    title: 'TruckerBook \u2014 \u041a\u0432\u0430\u0440\u0442\u0430\u043b\u044c\u043d\u0438\u0439 \u0437\u0432\u0456\u0442 IFTA',
    period: '\u041f\u0435\u0440\u0456\u043e\u0434',
    vehicle: '\u0422\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442',
    allVehicles: '\u0412\u0441\u0456 \u0422\u0417 (\u0437\u0432\u0456\u0442 \u043f\u043e \u043f\u0430\u0440\u043a\u0443)',
    generated: '\u0421\u0444\u043e\u0440\u043c\u043e\u0432\u0430\u043d\u043e',
    status: '\u0421\u0442\u0430\u0442\u0443\u0441',
    draft: '\u0427\u0415\u0420\u041d\u0415\u0422\u041a\u0410',
    final: '\u0424\u0406\u041d\u0410\u041b',
    totalMiles: '\u0412\u0441\u044c\u043e\u0433\u043e \u043c\u0438\u043b\u044c',
    totalGallons: '\u0412\u0441\u044c\u043e\u0433\u043e \u0433\u0430\u043b\u043e\u043d\u0456\u0432 \u043a\u0443\u043f\u043b\u0435\u043d\u043e',
    fleetMpg: '\u0421\u0435\u0440\u0435\u0434\u043d\u0456\u0439 MPG \u043f\u043e \u043f\u0430\u0440\u043a\u0443',
    totalTax: '\u041f\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0456 \u0437\u043e\u0431\u043e\u0432\'\u044f\u0437\u0430\u043d\u043d\u044f',
    totalSurcharge: '\u0414\u043e\u043f\u043b\u0430\u0442\u0438',
    totalCredits: '\u041a\u0440\u0435\u0434\u0438\u0442\u0438 (\u043f\u043e\u0434\u0430\u0442\u043e\u043a \u0441\u043f\u043b\u0430\u0447\u0435\u043d\u0438\u0439 \u043d\u0430 \u0410\u0417\u0421)',
    netBalance: '\u041f\u0406\u0414\u0421\u0423\u041c\u041e\u041a',
    oweNote: '\u0421\u0443\u043c\u0430 \u0434\u043e \u0441\u043f\u043b\u0430\u0442\u0438 IFTA',
    creditNote: '\u041a\u0440\u0435\u0434\u0438\u0442 / \u043f\u043e\u0432\u0435\u0440\u043d\u0435\u043d\u043d\u044f',
    credit: '(\u043a\u0440\u0435\u0434\u0438\u0442)',
    total: '\u0412\u0421\u042c\u041e\u0413\u041e',
    disclaimer: '\u0426\u0435\u0439 \u0437\u0432\u0456\u0442 \u0441\u0444\u043e\u0440\u043c\u043e\u0432\u0430\u043d\u043e TruckerBook \u0432\u0438\u043a\u043b\u044e\u0447\u043d\u043e \u0432 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u0439\u043d\u0438\u0445 \u0446\u0456\u043b\u044f\u0445. \u0412\u0456\u043d \u041d\u0415 \u0437\u0430\u043c\u0456\u043d\u044e\u0454 \u043f\u0440\u043e\u0444\u0435\u0441\u0456\u0439\u043d\u0443 \u043f\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0443 \u043f\u0456\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0443. \u041f\u0435\u0440\u0435\u0434 \u043f\u043e\u0434\u0430\u0447\u0435\u044e \u043f\u0435\u0440\u0435\u0432\u0456\u0440\u0442\u0435 \u0432\u0441\u0456 \u0446\u0438\u0444\u0440\u0438 \u0437 \u043b\u0456\u0446\u0435\u043d\u0437\u043e\u0432\u0430\u043d\u0438\u043c CPA \u0430\u0431\u043e EA.',
    footer: '\u0421\u0444\u043e\u0440\u043c\u043e\u0432\u0430\u043d\u043e TruckerBook | truckerbook-app.vercel.app',
    page: '\u0421\u0442\u043e\u0440.',
  },
}

// Fallback: any unrecognized language uses English labels
function getLabels(lang) {
  return PDF_LABELS[lang] || PDF_LABELS.en
}

function getPeriodLabel(quarter, year, lang) {
  const months = QUARTER_MONTHS[quarter]
  const range = (months && months[lang]) || months.en
  return `Q${quarter} ${year} (${range}, ${year})`
}

function fmtMoney(n) {
  if (n == null) return '\u2014'
  const abs = Math.abs(n).toFixed(2)
  return n < 0 ? '-$' + abs : '$' + abs
}

function isCurrentOrFutureQuarter(quarter, year) {
  const now = new Date()
  const curYear = now.getFullYear()
  const curQ = Math.ceil((now.getMonth() + 1) / 3)
  return year > curYear || (year === curYear && quarter >= curQ)
}

/**
 * Generate and download a professional IFTA quarterly report PDF.
 *
 * @param {Object} params
 * @param {Object} params.report - { states: Array, totals: Object } from buildQuarterlyReport
 * @param {number} params.quarter - 1-4
 * @param {number} params.year - e.g. 2026
 * @param {string} params.vehicleName - Vehicle label or null for fleet
 * @param {string} params.companyName - Company / user name
 * @param {string} params.language - 'en' | 'ru' | 'uk' | etc.
 */
export async function generateIftaPdf({ report, quarter, year, vehicleName, companyName, language }) {
  const { default: jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')
  const { robotoRegularBase64, robotoBoldBase64 } = await import('./roboto-font.js')

  const lang = language || 'en'
  const L = getLabels(lang)
  const isDraft = isCurrentOrFutureQuarter(quarter, year)

  // --- Create document (portrait for formal report) ---
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // Embed Roboto for Cyrillic support
  doc.addFileToVFS('Roboto-Regular.ttf', robotoRegularBase64)
  doc.addFont('Roboto-Regular.ttf', 'Roboto', 'normal')
  doc.addFileToVFS('Roboto-Bold.ttf', robotoBoldBase64)
  doc.addFont('Roboto-Bold.ttf', 'Roboto', 'bold')
  doc.setFont('Roboto', 'normal')

  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const marginL = 14
  const marginR = 14
  const contentW = pageW - marginL - marginR

  // ============================================================
  //  DRAFT WATERMARK (diagonal across center)
  // ============================================================
  const drawWatermark = () => {
    if (!isDraft) return
    doc.saveGraphicsState()
    doc.setGState(new doc.GState({ opacity: 0.06 }))
    doc.setFont('Roboto', 'bold')
    doc.setFontSize(72)
    doc.setTextColor(239, 68, 68)
    // Rotate text diagonally
    const cx = pageW / 2
    const cy = pageH / 2
    doc.text(L.draft, cx, cy, { align: 'center', angle: 45 })
    doc.restoreGraphicsState()
  }

  drawWatermark()

  // ============================================================
  //  HEADER
  // ============================================================
  let y = 16

  // Orange accent line
  doc.setFillColor(245, 158, 11)
  doc.rect(marginL, y - 2, contentW, 1, 'F')
  y += 6

  // Title
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(20, 20, 20)
  doc.text(L.title, marginL, y)
  y += 8

  // Company / user name
  if (companyName) {
    doc.setFont('Roboto', 'normal')
    doc.setFontSize(12)
    doc.setTextColor(60, 60, 60)
    doc.text(companyName, marginL, y)
    y += 6
  }

  // Meta info block
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  const periodStr = getPeriodLabel(quarter, year, lang)
  const vehicleStr = vehicleName || L.allVehicles
  const generatedStr = new Date().toLocaleString(lang === 'ru' ? 'ru-RU' : lang === 'uk' ? 'uk-UA' : 'en-US', {
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit',
  })

  const meta = [
    `${L.period}: ${periodStr}`,
    `${L.vehicle}: ${vehicleStr}`,
    `${L.generated}: ${generatedStr}`,
  ]
  for (const line of meta) {
    doc.text(line, marginL, y)
    y += 5
  }

  // Status badge
  if (isDraft) {
    doc.setFont('Roboto', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(239, 68, 68)
    doc.text(`${L.status}: ${L.draft}`, marginL, y)
  } else {
    doc.setFont('Roboto', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(34, 197, 94)
    doc.text(`${L.status}: ${L.final}`, marginL, y)
  }
  y += 8

  // Separator
  doc.setDrawColor(200, 200, 200)
  doc.setLineWidth(0.3)
  doc.line(marginL, y, pageW - marginR, y)
  y += 6

  // ============================================================
  //  MAIN TABLE — State-by-state breakdown
  // ============================================================
  // Column headers are always English (IFTA filing standard)
  const tableHead = [[
    'Jurisdiction',
    'Code',
    'Total Miles',
    'Taxable Gal',
    'Tax Rate\n($/gal)',
    'Tax Due ($)',
    'Surch. Rate',
    'Surch. Due ($)',
    'Net Due ($)',
  ]]

  const sortedStates = [...report.states].sort((a, b) => a.state_code.localeCompare(b.state_code))

  const tableBody = sortedStates.map(row => {
    const netStr = row.net_due != null
      ? (row.net_due < 0 ? fmtMoney(row.net_due) + ' ' + L.credit : fmtMoney(row.net_due))
      : '\u2014'
    return [
      row.state_name || row.state_code,
      row.state_code,
      row.miles.toFixed(1),
      row.gallons_consumed != null ? row.gallons_consumed.toFixed(1) : '\u2014',
      row.tax_rate != null ? '$' + row.tax_rate.toFixed(4) : '\u2014',
      row.tax_due != null ? fmtMoney(row.tax_due) : '\u2014',
      row.surcharge_rate != null ? '$' + row.surcharge_rate.toFixed(4) : '\u2014',
      row.surcharge_due != null ? fmtMoney(row.surcharge_due) : '\u2014',
      netStr,
    ]
  })

  // TOTAL row
  const totals = report.totals
  tableBody.push([
    { content: L.total, styles: { fontStyle: 'bold' } },
    '',
    { content: totals.total_miles.toFixed(1), styles: { fontStyle: 'bold' } },
    { content: totals.total_gallons > 0 ? (totals.total_miles / (totals.average_mpg || 6.5)).toFixed(1) : '\u2014', styles: { fontStyle: 'bold' } },
    '\u2014',
    { content: fmtMoney(totals.total_tax_due), styles: { fontStyle: 'bold' } },
    '\u2014',
    { content: fmtMoney(totals.total_surcharge), styles: { fontStyle: 'bold' } },
    { content: fmtMoney(totals.net_balance), styles: { fontStyle: 'bold', textColor: totals.net_balance <= 0 ? [34, 197, 94] : [239, 68, 68] } },
  ])

  autoTable(doc, {
    startY: y,
    head: tableHead,
    body: tableBody,
    styles: {
      fontSize: 8,
      cellPadding: 2.5,
      overflow: 'linebreak',
      font: 'Roboto',
      lineColor: [220, 220, 220],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: [245, 158, 11],
      textColor: 255,
      fontStyle: 'bold',
      font: 'Roboto',
      fontSize: 7.5,
      halign: 'center',
    },
    bodyStyles: {
      halign: 'right',
    },
    columnStyles: {
      0: { halign: 'left', cellWidth: 30 },  // Jurisdiction
      1: { halign: 'center', cellWidth: 14 }, // Code
    },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: marginL, right: marginR },
    // Color net_due cells for credit rows
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 8 && data.row.index < sortedStates.length) {
        const row = sortedStates[data.row.index]
        if (row && row.net_due != null && row.net_due < 0) {
          data.cell.styles.textColor = [34, 197, 94]
        }
      }
    },
  })

  y = doc.lastAutoTable.finalY + 10

  // ============================================================
  //  TOTALS SUMMARY CARD
  // ============================================================
  // Check if we need a new page
  if (y + 70 > pageH - 30) {
    doc.addPage()
    drawWatermark()
    y = 20
  }

  // Summary box background
  const boxH = 62
  doc.setFillColor(248, 249, 250)
  doc.setDrawColor(220, 220, 220)
  doc.roundedRect(marginL, y, contentW, boxH, 3, 3, 'FD')

  y += 8
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(20, 20, 20)

  const summaryX1 = marginL + 6
  const summaryX2 = marginL + contentW / 2 + 6

  const summaryLeft = [
    [L.totalMiles, totals.total_miles.toFixed(1)],
    [L.totalGallons, totals.total_gallons.toFixed(1)],
    [L.fleetMpg, totals.average_mpg != null ? totals.average_mpg.toFixed(1) : '\u2014'],
  ]

  // Calculate credits: sum of negative net_due values
  const totalCredits = sortedStates
    .filter(s => s.net_due != null && s.net_due < 0)
    .reduce((sum, s) => sum + Math.abs(s.net_due), 0)

  const summaryRight = [
    [L.totalTax, fmtMoney(totals.total_tax_due)],
    [L.totalSurcharge, fmtMoney(totals.total_surcharge)],
    [L.totalCredits, totalCredits > 0 ? fmtMoney(-totalCredits) : '$0.00'],
  ]

  doc.setFontSize(9)
  let sy = y
  for (const [label, value] of summaryLeft) {
    doc.setFont('Roboto', 'normal')
    doc.setTextColor(100, 100, 100)
    doc.text(label + ':', summaryX1, sy)
    doc.setFont('Roboto', 'bold')
    doc.setTextColor(20, 20, 20)
    doc.text(value, summaryX1 + 60, sy)
    sy += 6
  }

  sy = y
  for (const [label, value] of summaryRight) {
    doc.setFont('Roboto', 'normal')
    doc.setTextColor(100, 100, 100)
    doc.text(label + ':', summaryX2, sy)
    doc.setFont('Roboto', 'bold')
    doc.setTextColor(20, 20, 20)
    doc.text(value, summaryX2 + 68, sy)
    sy += 6
  }

  // Net balance — large, colored
  sy = y + 26
  doc.setDrawColor(200, 200, 200)
  doc.line(summaryX1, sy, marginL + contentW - 6, sy)
  sy += 8

  doc.setFont('Roboto', 'bold')
  doc.setFontSize(14)
  const netColor = totals.net_balance <= 0 ? [34, 197, 94] : [239, 68, 68]
  doc.setTextColor(...netColor)
  doc.text(`${L.netBalance}: ${fmtMoney(totals.net_balance)}`, summaryX1, sy)

  // Explanatory note
  doc.setFontSize(8)
  doc.setFont('Roboto', 'normal')
  doc.setTextColor(120, 120, 120)
  const balanceNote = totals.net_balance > 0 ? L.oweNote : L.creditNote
  doc.text(balanceNote, summaryX1, sy + 5)

  y += boxH + 10

  // ============================================================
  //  FOOTER — Disclaimer + branding
  // ============================================================
  if (y + 30 > pageH - 10) {
    doc.addPage()
    drawWatermark()
    y = 20
  }

  // Disclaimer
  doc.setFont('Roboto', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(140, 140, 140)
  const disclaimerLines = doc.splitTextToSize(L.disclaimer, contentW)
  doc.text(disclaimerLines, marginL, y)
  y += disclaimerLines.length * 3.5 + 4

  // Footer line
  doc.setDrawColor(220, 220, 220)
  doc.line(marginL, y, pageW - marginR, y)
  y += 4
  doc.setFontSize(7)
  doc.setTextColor(160, 160, 160)
  doc.text(L.footer, marginL, y)
  doc.text(`${L.page} 1`, pageW - marginR, y, { align: 'right' })

  // ============================================================
  //  SAVE
  // ============================================================
  const safeName = (companyName || 'Report').replace(/[^a-zA-Z0-9\u0400-\u04FF]/g, '_').slice(0, 30)
  const vehicleSuffix = vehicleName ? vehicleName.replace(/[^a-zA-Z0-9\u0400-\u04FF]/g, '_').slice(0, 20) : 'AllVehicles'
  const filename = `IFTA_Q${quarter}_${year}_${safeName}_${vehicleSuffix}.pdf`

  doc.save(filename)
}
