/**
 * Mileage Log — PDF & Excel Export
 * Generates an IRS-ready mileage log document.
 */
import * as XLSX from 'xlsx'

const PDF_LABELS = {
  en: {
    title: 'TruckerBook \u2014 Mileage Log',
    subtitle: 'IRS Business Mileage Record',
    period: 'Period',
    generated: 'Generated',
    date: 'Date',
    origin: 'Origin',
    destination: 'Destination',
    purpose: 'Business Purpose',
    miles: 'Miles',
    totalBusiness: 'Total Business Miles',
    totalPersonal: 'Total Personal Miles',
    businessPct: 'Business Use Percentage',
    disclaimer: 'This mileage log is generated by TruckerBook for record-keeping purposes only. Verify all entries before submitting to the IRS. Consult a qualified tax professional.',
    footer: 'Generated by TruckerBook | truckerbook-app.vercel.app',
    page: 'Page',
  },
  ru: {
    title: 'TruckerBook \u2014 \u0416\u0443\u0440\u043d\u0430\u043b \u043f\u0440\u043e\u0431\u0435\u0433\u0430',
    subtitle: '\u0423\u0447\u0451\u0442 \u0434\u0435\u043b\u043e\u0432\u044b\u0445 \u043c\u0438\u043b\u044c \u0434\u043b\u044f IRS',
    period: '\u041f\u0435\u0440\u0438\u043e\u0434',
    generated: '\u0421\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d',
    date: '\u0414\u0430\u0442\u0430',
    origin: '\u041e\u0442\u043a\u0443\u0434\u0430',
    destination: '\u041a\u0443\u0434\u0430',
    purpose: '\u0426\u0435\u043b\u044c \u043f\u043e\u0435\u0437\u0434\u043a\u0438',
    miles: '\u041c\u0438\u043b\u0438',
    totalBusiness: '\u0414\u0435\u043b\u043e\u0432\u044b\u0435 \u043c\u0438\u043b\u0438',
    totalPersonal: '\u041b\u0438\u0447\u043d\u044b\u0435 \u043c\u0438\u043b\u0438',
    businessPct: '\u0414\u0435\u043b\u043e\u0432\u043e\u0439 %',
    disclaimer: '\u042d\u0442\u043e\u0442 \u0436\u0443\u0440\u043d\u0430\u043b \u0441\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d TruckerBook \u0438\u0441\u043a\u043b\u044e\u0447\u0438\u0442\u0435\u043b\u044c\u043d\u043e \u0434\u043b\u044f \u0443\u0447\u0451\u0442\u0430. \u041f\u0440\u043e\u0432\u0435\u0440\u044c\u0442\u0435 \u0432\u0441\u0435 \u0437\u0430\u043f\u0438\u0441\u0438 \u043f\u0435\u0440\u0435\u0434 \u043f\u043e\u0434\u0430\u0447\u0435\u0439 \u0432 IRS.',
    footer: '\u0421\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u043e TruckerBook | truckerbook-app.vercel.app',
    page: '\u0421\u0442\u0440.',
  },
}

function getLabels(lang) {
  return PDF_LABELS[lang] || PDF_LABELS.en
}

function fmtDate(d) {
  if (!d) return ''
  return new Date(d + 'T00:00:00').toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' })
}

export async function generateMileageLogPdf(entries, summary, periodLabel, lang) {
  const { default: jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')
  const L = getLabels(lang)

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })
  const pageW = doc.internal.pageSize.getWidth()
  const margin = 14

  // Header
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(L.title, margin, 20)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(L.subtitle, margin, 27)

  doc.setFontSize(9)
  doc.text(`${L.period}: ${periodLabel}`, margin, 35)
  doc.text(`${L.generated}: ${new Date().toLocaleDateString()}`, pageW - margin, 35, { align: 'right' })

  // Table
  const head = [[L.date, L.destination, L.purpose, L.miles]]
  const body = entries.map(e => [
    fmtDate(e.date),
    (e.origin || '') + (e.origin && e.destination ? ' \u2192 ' : '') + (e.destination || ''),
    e.purpose_label || e.business_purpose || '',
    (e.miles || 0).toLocaleString('en-US', { minimumFractionDigits: 1, maximumFractionDigits: 1 }),
  ])

  autoTable(doc, {
    startY: 40,
    head,
    body,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 25 },
      3: { halign: 'right', cellWidth: 20 },
    },
    margin: { left: margin, right: margin },
    didDrawPage: (data) => {
      const pageNum = doc.internal.getNumberOfPages()
      doc.setFontSize(7)
      doc.setTextColor(130)
      doc.text(`${L.footer}  |  ${L.page} ${pageNum}`, pageW / 2, doc.internal.pageSize.getHeight() - 8, { align: 'center' })
    },
  })

  // Summary section
  let y = doc.lastAutoTable.finalY + 12
  if (y > doc.internal.pageSize.getHeight() - 50) {
    doc.addPage()
    y = 20
  }

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0)
  doc.text(`${L.totalBusiness}: ${summary.businessMiles.toLocaleString('en-US', { minimumFractionDigits: 1 })}`, margin, y)
  y += 6
  doc.text(`${L.totalPersonal}: ${summary.personalMiles.toLocaleString('en-US', { minimumFractionDigits: 1 })}`, margin, y)
  y += 6
  doc.text(`${L.businessPct}: ${summary.businessPct.toFixed(1)}%`, margin, y)
  y += 10

  // Disclaimer
  doc.setFontSize(7)
  doc.setFont('helvetica', 'italic')
  doc.setTextColor(130)
  const disclaimerLines = doc.splitTextToSize(L.disclaimer, pageW - margin * 2)
  doc.text(disclaimerLines, margin, y)

  doc.save(`MileageLog_${periodLabel.replace(/\s/g, '_')}.pdf`)
}

export function exportMileageLogExcel(entries, summary, periodLabel) {
  const headers = ['Date', 'Origin', 'Destination', 'Business Purpose', 'Miles', 'Type']
  const rows = entries.map(e => [
    e.date || '',
    e.origin || '',
    e.destination || '',
    e.purpose_label || e.business_purpose || '',
    e.miles || 0,
    e.business_purpose === 'Personal' ? 'Personal' : 'Business',
  ])

  const ws = XLSX.utils.aoa_to_sheet([headers, ...rows])

  // Totals rows
  const totalRow = rows.length + 2
  XLSX.utils.sheet_add_aoa(ws, [
    [],
    ['', '', '', 'Total Business Miles', summary.businessMiles],
    ['', '', '', 'Total Personal Miles', summary.personalMiles],
    ['', '', '', 'Business Use %', summary.businessPct / 100],
  ], { origin: `A${totalRow}` })

  // Format business pct as percentage
  const pctCell = XLSX.utils.encode_cell({ r: totalRow + 2, c: 4 })
  if (ws[pctCell]) ws[pctCell].z = '0.0%'

  // Column widths
  ws['!cols'] = [
    { wch: 12 }, { wch: 20 }, { wch: 20 }, { wch: 18 }, { wch: 10 }, { wch: 10 },
  ]

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Mileage Log')
  XLSX.writeFile(wb, `MileageLog_${periodLabel.replace(/\s/g, '_')}.xlsx`)
}
