/**
 * Shared branded PDF header/footer for TruckerBook owner_operator exports.
 * Keeps all tax/mileage/IFTA/report PDFs visually consistent.
 */

// Brand accent — same orange as UI (#F59E0B)
export const BRAND_COLOR = [245, 158, 11]
const DIVIDER_COLOR = [230, 230, 230]
const SUBTITLE_COLOR = [100, 100, 100]
const FOOTER_COLOR = [150, 150, 150]

const BAR_HEIGHT = 14
const MARGIN_X = 14
const LOGO_TEXT = 'TruckerBook'

/**
 * Draw the branded header on the current page.
 * Returns the Y coordinate where subsequent content should start.
 *
 * @param {jsPDF} doc
 * @param {Object} opts
 * @param {string} [opts.title]    Document title (e.g. "Annual Tax Report")
 * @param {string} [opts.subtitle] Grey line under the bar (e.g. "IRS Schedule C")
 * @param {string|number} [opts.year] Period label shown on the right (e.g. "FY 2026")
 * @param {string} [opts.font='helvetica'] Font family to use
 * @returns {number} y coordinate below header for content
 */
export function renderPdfHeader(doc, { title, subtitle, year, font = 'helvetica' } = {}) {
  const pageW = doc.internal.pageSize.getWidth()

  doc.setFillColor(...BRAND_COLOR)
  doc.rect(0, 0, pageW, BAR_HEIGHT, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFont(font, 'bold')
  doc.setFontSize(13)
  doc.text(LOGO_TEXT, MARGIN_X, 9)

  if (title) {
    doc.setFont(font, 'normal')
    doc.setFontSize(11)
    doc.text(String(title), pageW / 2, 9, { align: 'center' })
  }

  if (year != null && year !== '') {
    doc.setFont(font, 'normal')
    doc.setFontSize(10)
    doc.text(String(year), pageW - MARGIN_X, 9, { align: 'right' })
  }

  let y = BAR_HEIGHT + 5
  if (subtitle) {
    doc.setFont(font, 'normal')
    doc.setFontSize(9)
    doc.setTextColor(...SUBTITLE_COLOR)
    doc.text(String(subtitle), MARGIN_X, y)
    y += 4
  }

  doc.setDrawColor(...DIVIDER_COLOR)
  doc.setLineWidth(0.3)
  doc.line(MARGIN_X, y, pageW - MARGIN_X, y)

  doc.setTextColor(20, 20, 20)
  doc.setFont(font, 'normal')

  return y + 6
}

/**
 * Add a branded footer to every page.
 * Must be called AFTER all content is rendered so page count is known.
 *
 * @param {jsPDF} doc
 * @param {Object} [opts]
 * @param {string} [opts.font='helvetica']
 * @param {string} [opts.date] Override date text (defaults to locale today)
 */
export function renderPdfFooter(doc, { font = 'helvetica', date } = {}) {
  const pageH = doc.internal.pageSize.getHeight()
  const pageW = doc.internal.pageSize.getWidth()
  const total = doc.internal.getNumberOfPages()
  const today = date || new Date().toLocaleDateString('en-US')
  const line = `Generated by TruckerBook \u00b7 truckerbook-app.vercel.app \u00b7 ${today}`

  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    doc.setFont(font, 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...FOOTER_COLOR)
    doc.text(line, pageW / 2, pageH - 8, { align: 'center' })
    doc.text(`${i} / ${total}`, pageW - MARGIN_X, pageH - 8, { align: 'right' })
  }
}
