/**
 * Tax Summary (Schedule C) — PDF & Excel Export
 * Generates a CPA-ready annual tax summary document.
 */
import * as XLSX from 'xlsx'

const PDF_LABELS = {
  en: {
    title: 'TruckerBook \u2014 Annual Tax Summary',
    subtitle: 'IRS Schedule C \u2014 Profit or Loss from Business',
    taxYear: 'Tax Year',
    generated: 'Generated',
    grossIncome: 'GROSS INCOME',
    expenses: 'BUSINESS EXPENSES (Schedule C)',
    fuel: 'Fuel',
    repairs: 'Repairs & Maintenance',
    insurance: 'Insurance',
    lease: 'Truck Payments / Lease',
    tolls: 'Tolls',
    parking: 'Parking',
    otherExpenses: 'Other Expenses',
    totalExpenses: 'TOTAL EXPENSES',
    perDiem: 'Per Diem Deduction',
    depreciation: 'Truck Depreciation',
    totalDeductions: 'TOTAL DEDUCTIONS',
    netProfit: 'NET PROFIT (Loss)',
    taxEstimates: 'ESTIMATED TAX LIABILITY',
    seTax: 'Self-Employment Tax',
    incomeTax: 'Federal Income Tax',
    totalTax: 'TOTAL ESTIMATED TAX',
    disclaimer: 'This report is generated by TruckerBook for informational purposes only. It is NOT a substitute for professional tax preparation. Verify all figures with a licensed CPA or EA before filing.',
    footer: 'Generated by TruckerBook | truckerbook-app.vercel.app',
    page: 'Page',
  },
  ru: {
    title: 'TruckerBook \u2014 \u0413\u043e\u0434\u043e\u0432\u043e\u0439 \u043d\u0430\u043b\u043e\u0433\u043e\u0432\u044b\u0439 \u043e\u0442\u0447\u0451\u0442',
    subtitle: 'IRS Schedule C \u2014 \u041f\u0440\u0438\u0431\u044b\u043b\u044c / \u0443\u0431\u044b\u0442\u043e\u043a \u043e\u0442 \u0431\u0438\u0437\u043d\u0435\u0441\u0430',
    taxYear: '\u041d\u0430\u043b\u043e\u0433\u043e\u0432\u044b\u0439 \u0433\u043e\u0434',
    generated: '\u0421\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d',
    grossIncome: '\u0412\u0410\u041b\u041e\u0412\u042b\u0419 \u0414\u041e\u0425\u041e\u0414',
    expenses: '\u0420\u0410\u0421\u0425\u041e\u0414\u042b (Schedule C)',
    fuel: '\u0422\u043e\u043f\u043b\u0438\u0432\u043e',
    repairs: '\u0420\u0435\u043c\u043e\u043d\u0442 \u0438 \u0422\u041e',
    insurance: '\u0421\u0442\u0440\u0430\u0445\u043e\u0432\u0430\u043d\u0438\u0435',
    lease: '\u041f\u043b\u0430\u0442\u0435\u0436\u0438 \u0437\u0430 \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442 / \u041b\u0438\u0437\u0438\u043d\u0433',
    tolls: '\u041f\u043b\u0430\u0442\u043d\u044b\u0435 \u0434\u043e\u0440\u043e\u0433\u0438',
    parking: '\u041f\u0430\u0440\u043a\u043e\u0432\u043a\u0430',
    otherExpenses: '\u041f\u0440\u043e\u0447\u0438\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b',
    totalExpenses: '\u0418\u0422\u041e\u0413\u041e \u0420\u0410\u0421\u0425\u041e\u0414\u042b',
    perDiem: '\u0412\u044b\u0447\u0435\u0442 Per Diem',
    depreciation: '\u0410\u043c\u043e\u0440\u0442\u0438\u0437\u0430\u0446\u0438\u044f \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u0430',
    totalDeductions: '\u0412\u0421\u0415\u0413\u041e \u0412\u042b\u0427\u0415\u0422\u042b',
    netProfit: '\u0427\u0418\u0421\u0422\u0410\u042f \u041f\u0420\u0418\u0411\u042b\u041b\u042c (\u0423\u0431\u044b\u0442\u043e\u043a)',
    taxEstimates: '\u041e\u0426\u0415\u041d\u041a\u0410 \u041d\u0410\u041b\u041e\u0413\u041e\u0412',
    seTax: '\u041d\u0430\u043b\u043e\u0433 \u043d\u0430 \u0441\u0430\u043c\u043e\u0437\u0430\u043d\u044f\u0442\u043e\u0441\u0442\u044c',
    incomeTax: '\u0424\u0435\u0434\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0439 \u043f\u043e\u0434\u043e\u0445\u043e\u0434\u043d\u044b\u0439 \u043d\u0430\u043b\u043e\u0433',
    totalTax: '\u0418\u0422\u041e\u0413\u041e \u041d\u0410\u041b\u041e\u0413',
    disclaimer: '\u042d\u0442\u043e\u0442 \u043e\u0442\u0447\u0451\u0442 \u0441\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d TruckerBook \u0438\u0441\u043a\u043b\u044e\u0447\u0438\u0442\u0435\u043b\u044c\u043d\u043e \u0432 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0445 \u0446\u0435\u043b\u044f\u0445. \u041e\u043d \u041d\u0415 \u0437\u0430\u043c\u0435\u043d\u044f\u0435\u0442 \u043f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u0443\u044e \u043d\u0430\u043b\u043e\u0433\u043e\u0432\u0443\u044e \u043f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0443. \u041f\u0435\u0440\u0435\u0434 \u043f\u043e\u0434\u0430\u0447\u0435\u0439 \u043f\u0440\u043e\u0432\u0435\u0440\u044c\u0442\u0435 \u0432\u0441\u0435 \u0446\u0438\u0444\u0440\u044b \u0441 \u043b\u0438\u0446\u0435\u043d\u0437\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u043c CPA \u0438\u043b\u0438 EA.',
    footer: '\u0421\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u043e TruckerBook | truckerbook-app.vercel.app',
    page: '\u0421\u0442\u0440.',
  },
  uk: {
    title: 'TruckerBook \u2014 \u0420\u0456\u0447\u043d\u0438\u0439 \u043f\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0438\u0439 \u0437\u0432\u0456\u0442',
    subtitle: 'IRS Schedule C \u2014 \u041f\u0440\u0438\u0431\u0443\u0442\u043e\u043a / \u0437\u0431\u0438\u0442\u043e\u043a \u0432\u0456\u0434 \u0431\u0456\u0437\u043d\u0435\u0441\u0443',
    taxYear: '\u041f\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0438\u0439 \u0440\u0456\u043a',
    generated: '\u0421\u0444\u043e\u0440\u043c\u043e\u0432\u0430\u043d\u043e',
    grossIncome: '\u0412\u0410\u041b\u041e\u0412\u0418\u0419 \u0414\u041e\u0425\u0406\u0414',
    expenses: '\u0412\u0418\u0422\u0420\u0410\u0422\u0418 (Schedule C)',
    fuel: '\u041f\u0430\u043b\u0438\u0432\u043e',
    repairs: '\u0420\u0435\u043c\u043e\u043d\u0442 \u0456 \u0422\u041e',
    insurance: '\u0421\u0442\u0440\u0430\u0445\u0443\u0432\u0430\u043d\u043d\u044f',
    lease: '\u041f\u043b\u0430\u0442\u0435\u0436\u0456 \u0437\u0430 \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442 / \u041b\u0456\u0437\u0438\u043d\u0433',
    tolls: '\u041f\u043b\u0430\u0442\u043d\u0456 \u0434\u043e\u0440\u043e\u0433\u0438',
    parking: '\u041f\u0430\u0440\u043a\u0443\u0432\u0430\u043d\u043d\u044f',
    otherExpenses: '\u0406\u043d\u0448\u0456 \u0432\u0438\u0442\u0440\u0430\u0442\u0438',
    totalExpenses: '\u0412\u0421\u042c\u041e\u0413\u041e \u0412\u0418\u0422\u0420\u0410\u0422',
    perDiem: '\u0412\u0438\u0440\u0430\u0445\u0443\u0432\u0430\u043d\u043d\u044f Per Diem',
    depreciation: '\u0410\u043c\u043e\u0440\u0442\u0438\u0437\u0430\u0446\u0456\u044f \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u0443',
    totalDeductions: '\u0412\u0421\u042c\u041e\u0413\u041e \u0412\u0418\u0420\u0410\u0425\u0423\u0412\u0410\u041d\u042c',
    netProfit: '\u0427\u0418\u0421\u0422\u0418\u0419 \u041f\u0420\u0418\u0411\u0423\u0422\u041e\u041a (\u0417\u0431\u0438\u0442\u043e\u043a)',
    taxEstimates: '\u041e\u0426\u0406\u041d\u041a\u0410 \u041f\u041e\u0414\u0410\u0422\u041a\u0406\u0412',
    seTax: '\u041f\u043e\u0434\u0430\u0442\u043e\u043a \u043d\u0430 \u0441\u0430\u043c\u043e\u0437\u0430\u0439\u043d\u044f\u0442\u0456\u0441\u0442\u044c',
    incomeTax: '\u0424\u0435\u0434\u0435\u0440\u0430\u043b\u044c\u043d\u0438\u0439 \u043f\u0440\u0438\u0431\u0443\u0442\u043a\u043e\u0432\u0438\u0439 \u043f\u043e\u0434\u0430\u0442\u043e\u043a',
    totalTax: '\u0412\u0421\u042c\u041e\u0413\u041e \u041f\u041e\u0414\u0410\u0422\u041e\u041a',
    disclaimer: '\u0426\u0435\u0439 \u0437\u0432\u0456\u0442 \u0441\u0444\u043e\u0440\u043c\u043e\u0432\u0430\u043d\u043e TruckerBook \u0432\u0438\u043a\u043b\u044e\u0447\u043d\u043e \u0432 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u0439\u043d\u0438\u0445 \u0446\u0456\u043b\u044f\u0445. \u0412\u0456\u043d \u041d\u0415 \u0437\u0430\u043c\u0456\u043d\u044e\u0454 \u043f\u0440\u043e\u0444\u0435\u0441\u0456\u0439\u043d\u0443 \u043f\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0443 \u043f\u0456\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0443. \u041f\u0435\u0440\u0435\u0434 \u043f\u043e\u0434\u0430\u0447\u0435\u044e \u043f\u0435\u0440\u0435\u0432\u0456\u0440\u0442\u0435 \u0432\u0441\u0456 \u0446\u0438\u0444\u0440\u0438 \u0437 \u043b\u0456\u0446\u0435\u043d\u0437\u043e\u0432\u0430\u043d\u0438\u043c CPA \u0430\u0431\u043e EA.',
    footer: '\u0421\u0444\u043e\u0440\u043c\u043e\u0432\u0430\u043d\u043e TruckerBook | truckerbook-app.vercel.app',
    page: '\u0421\u0442\u043e\u0440.',
  },
  es: {
    title: 'TruckerBook \u2014 Resumen Fiscal Anual',
    subtitle: 'IRS Schedule C \u2014 Ganancias o P\u00e9rdidas del Negocio',
    taxYear: 'A\u00f1o Fiscal',
    generated: 'Generado',
    grossIncome: 'INGRESO BRUTO',
    expenses: 'GASTOS DE NEGOCIO (Schedule C)',
    fuel: 'Combustible',
    repairs: 'Reparaciones y Mantenimiento',
    insurance: 'Seguro',
    lease: 'Pagos del cami\u00f3n / Leasing',
    tolls: 'Peajes',
    parking: 'Estacionamiento',
    otherExpenses: 'Otros gastos',
    totalExpenses: 'TOTAL GASTOS',
    perDiem: 'Deducci\u00f3n Per Diem',
    depreciation: 'Depreciaci\u00f3n del cami\u00f3n',
    totalDeductions: 'TOTAL DEDUCCIONES',
    netProfit: 'GANANCIA NETA (P\u00e9rdida)',
    taxEstimates: 'IMPUESTO ESTIMADO',
    seTax: 'Impuesto de autoempleo',
    incomeTax: 'Impuesto sobre la renta federal',
    totalTax: 'TOTAL IMPUESTO',
    disclaimer: 'Este informe ha sido generado por TruckerBook \u00fanicamente con fines informativos. NO sustituye la preparaci\u00f3n fiscal profesional. Verifique todas las cifras con un CPA o EA autorizado antes de presentar.',
    footer: 'Generado por TruckerBook | truckerbook-app.vercel.app',
    page: 'P\u00e1g.',
  },
  de: {
    title: 'TruckerBook \u2014 J\u00e4hrliche Steuer\u00fcbersicht',
    subtitle: 'IRS Schedule C \u2014 Gewinn oder Verlust aus Gesch\u00e4ftst\u00e4tigkeit',
    taxYear: 'Steuerjahr',
    generated: 'Erstellt',
    grossIncome: 'BRUTTOEINKOMMEN',
    expenses: 'BETRIEBSAUSGABEN (Schedule C)',
    fuel: 'Kraftstoff',
    repairs: 'Reparaturen & Wartung',
    insurance: 'Versicherung',
    lease: 'LKW-Zahlungen / Leasing',
    tolls: 'Mautgeb\u00fchren',
    parking: 'Parken',
    otherExpenses: 'Sonstige Ausgaben',
    totalExpenses: 'AUSGABEN GESAMT',
    perDiem: 'Per Diem Abzug',
    depreciation: 'LKW-Abschreibung',
    totalDeductions: 'ABZ\u00dcGE GESAMT',
    netProfit: 'NETTOGEWINN (Verlust)',
    taxEstimates: 'GESCH\u00c4TZTE STEUER',
    seTax: 'Selbstst\u00e4ndigensteuer',
    incomeTax: 'Bundeseinkommensteuer',
    totalTax: 'STEUER GESAMT',
    disclaimer: 'Dieser Bericht wurde von TruckerBook ausschlie\u00dflich zu Informationszwecken erstellt. Er ist KEIN Ersatz f\u00fcr professionelle Steuerberatung. \u00dcberpr\u00fcfen Sie alle Zahlen mit einem lizenzierten Steuerberater vor der Einreichung.',
    footer: 'Erstellt von TruckerBook | truckerbook-app.vercel.app',
    page: 'Seite',
  },
  fr: {
    title: 'TruckerBook \u2014 R\u00e9sum\u00e9 Fiscal Annuel',
    subtitle: 'IRS Schedule C \u2014 B\u00e9n\u00e9fice ou Perte d\u2019Entreprise',
    taxYear: 'Ann\u00e9e fiscale',
    generated: 'G\u00e9n\u00e9r\u00e9',
    grossIncome: 'REVENU BRUT',
    expenses: 'D\u00c9PENSES D\u2019ENTREPRISE (Schedule C)',
    fuel: 'Carburant',
    repairs: 'R\u00e9parations & Entretien',
    insurance: 'Assurance',
    lease: 'Paiements camion / Leasing',
    tolls: 'P\u00e9ages',
    parking: 'Stationnement',
    otherExpenses: 'Autres d\u00e9penses',
    totalExpenses: 'TOTAL D\u00c9PENSES',
    perDiem: 'D\u00e9duction Per Diem',
    depreciation: 'Amortissement du camion',
    totalDeductions: 'TOTAL D\u00c9DUCTIONS',
    netProfit: 'B\u00c9N\u00c9FICE NET (Perte)',
    taxEstimates: 'IMP\u00d4T ESTIM\u00c9',
    seTax: 'Imp\u00f4t sur le travail ind\u00e9pendant',
    incomeTax: 'Imp\u00f4t f\u00e9d\u00e9ral sur le revenu',
    totalTax: 'TOTAL IMP\u00d4T',
    disclaimer: 'Ce rapport a \u00e9t\u00e9 g\u00e9n\u00e9r\u00e9 par TruckerBook \u00e0 titre informatif uniquement. Il NE remplace PAS la pr\u00e9paration fiscale professionnelle. V\u00e9rifiez tous les chiffres avec un CPA ou EA agr\u00e9\u00e9 avant de d\u00e9poser.',
    footer: 'G\u00e9n\u00e9r\u00e9 par TruckerBook | truckerbook-app.vercel.app',
    page: 'Page',
  },
  tr: {
    title: 'TruckerBook \u2014 Y\u0131ll\u0131k Vergi \u00d6zeti',
    subtitle: 'IRS Schedule C \u2014 \u0130\u015f Kar\u0131 veya Zarar\u0131',
    taxYear: 'Vergi Y\u0131l\u0131',
    generated: 'Olu\u015fturuldu',
    grossIncome: 'BR\u00dcT GEL\u0130R',
    expenses: '\u0130\u015e G\u0130DERLER\u0130 (Schedule C)',
    fuel: 'Yak\u0131t',
    repairs: 'Onar\u0131m & Bak\u0131m',
    insurance: 'Sigorta',
    lease: 'Kamyon \u00f6demeleri / Leasing',
    tolls: 'Ge\u00e7i\u015f \u00fccretleri',
    parking: 'Otopark',
    otherExpenses: 'Di\u011fer giderler',
    totalExpenses: 'TOPLAM G\u0130DERLER',
    perDiem: 'Per Diem kesintisi',
    depreciation: 'Kamyon amortismas\u0131',
    totalDeductions: 'TOPLAM KES\u0130NT\u0130LER',
    netProfit: 'NET KAR (Zarar)',
    taxEstimates: 'TAHM\u0130N\u0130 VERG\u0130',
    seTax: 'Serbest meslek vergisi',
    incomeTax: 'Federal gelir vergisi',
    totalTax: 'TOPLAM VERG\u0130',
    disclaimer: 'Bu rapor TruckerBook taraf\u0131ndan yaln\u0131zca bilgi ama\u00e7l\u0131 olu\u015fturulmu\u015ftur. Profesyonel vergi haz\u0131rl\u0131\u011f\u0131n\u0131n yerine GE\u00c7MEZ. Beyanname vermeden \u00f6nce t\u00fcm rakamlar\u0131 lisansl\u0131 bir CPA veya EA ile do\u011frulay\u0131n.',
    footer: 'TruckerBook taraf\u0131ndan olu\u015fturuldu | truckerbook-app.vercel.app',
    page: 'Sayfa',
  },
  pl: {
    title: 'TruckerBook \u2014 Roczne Podsumowanie Podatkowe',
    subtitle: 'IRS Schedule C \u2014 Zysk lub Strata z Dzia\u0142alno\u015bci',
    taxYear: 'Rok podatkowy',
    generated: 'Wygenerowano',
    grossIncome: 'DOCH\u00d3D BRUTTO',
    expenses: 'WYDATKI BIZNESOWE (Schedule C)',
    fuel: 'Paliwo',
    repairs: 'Naprawy i konserwacja',
    insurance: 'Ubezpieczenie',
    lease: 'P\u0142atno\u015bci za ci\u0119\u017car\u00f3wk\u0119 / Leasing',
    tolls: 'Op\u0142aty drogowe',
    parking: 'Parking',
    otherExpenses: 'Inne wydatki',
    totalExpenses: 'RAZEM WYDATKI',
    perDiem: 'Odliczenie Per Diem',
    depreciation: 'Amortyzacja ci\u0119\u017car\u00f3wki',
    totalDeductions: 'RAZEM ODLICZENIA',
    netProfit: 'ZYSK NETTO (Strata)',
    taxEstimates: 'SZACUNKOWY PODATEK',
    seTax: 'Podatek od samozatrudnienia',
    incomeTax: 'Federalny podatek dochodowy',
    totalTax: 'RAZEM PODATEK',
    disclaimer: 'Ten raport zosta\u0142 wygenerowany przez TruckerBook wy\u0142\u0105cznie w celach informacyjnych. NIE zast\u0119puje profesjonalnego przygotowania podatkowego. Przed z\u0142o\u017ceniem zweryfikuj wszystkie dane z licencjonowanym CPA lub EA.',
    footer: 'Wygenerowano przez TruckerBook | truckerbook-app.vercel.app',
    page: 'Str.',
  },
}

function getLabels(lang) {
  return PDF_LABELS[lang] || PDF_LABELS.en
}

function fmtMoney(n) {
  if (n == null) return '\u2014'
  const abs = Math.abs(n).toFixed(2)
  return n < 0 ? '-$' + abs : '$' + abs
}

/**
 * Generate and download a professional Tax Summary PDF.
 */
export async function generateTaxSummaryPdf({
  year, income, expenses, perDiem, depreciation,
  totalExpenses, totalDeductions, netProfit,
  seTax, seTaxRate, incomeTax, incomeTaxRate, totalTax,
  language, companyName,
}) {
  const { default: jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')
  const { robotoRegularBase64, robotoBoldBase64 } = await import('./roboto-font.js')

  const lang = language || 'en'
  const L = getLabels(lang)

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // Embed Roboto for Cyrillic
  doc.addFileToVFS('Roboto-Regular.ttf', robotoRegularBase64)
  doc.addFont('Roboto-Regular.ttf', 'Roboto', 'normal')
  doc.addFileToVFS('Roboto-Bold.ttf', robotoBoldBase64)
  doc.addFont('Roboto-Bold.ttf', 'Roboto', 'bold')
  doc.setFont('Roboto', 'normal')

  const pageW = doc.internal.pageSize.getWidth()
  const marginL = 14
  const marginR = 14
  const contentW = pageW - marginL - marginR

  let y = 16

  // Orange accent line
  doc.setFillColor(245, 158, 11)
  doc.rect(marginL, y - 2, contentW, 1, 'F')
  y += 6

  // Title
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(20, 20, 20)
  doc.text(L.title, marginL, y)
  y += 7

  // Subtitle
  doc.setFont('Roboto', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(L.subtitle, marginL, y)
  y += 8

  // Meta: year + generated date
  if (companyName) {
    doc.text(companyName, marginL, y)
    y += 5
  }
  doc.setFontSize(10)
  doc.setTextColor(60, 60, 60)
  doc.text(`${L.taxYear}: ${year}`, marginL, y)
  doc.text(`${L.generated}: ${new Date().toLocaleDateString('en-US')}`, pageW - marginR, y, { align: 'right' })
  y += 8

  // Separator
  doc.setDrawColor(200, 200, 200)
  doc.line(marginL, y, pageW - marginR, y)
  y += 8

  // === GROSS INCOME ===
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(34, 197, 94)
  doc.text(L.grossIncome, marginL, y)
  doc.text(fmtMoney(income), pageW - marginR, y, { align: 'right' })
  y += 10

  // === EXPENSES TABLE ===
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(20, 20, 20)
  doc.text(L.expenses, marginL, y)
  y += 2

  const expenseRows = expenses.map(e => [e.label, fmtMoney(e.value)])
  expenseRows.push(['', ''])
  expenseRows.push([L.totalExpenses, fmtMoney(totalExpenses)])

  autoTable(doc, {
    startY: y,
    head: [],
    body: expenseRows,
    theme: 'plain',
    styles: { font: 'Roboto', fontSize: 10, cellPadding: { top: 2, bottom: 2, left: 4, right: 4 } },
    columnStyles: {
      0: { cellWidth: contentW * 0.65 },
      1: { cellWidth: contentW * 0.35, halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: marginL, right: marginR },
    didParseCell: (data) => {
      // Bold total row
      if (data.row.index === expenseRows.length - 1) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = [239, 68, 68]
      }
    },
  })

  y = doc.lastAutoTable.finalY + 8

  // === ADDITIONAL DEDUCTIONS ===
  const deductionRows = [
    [L.perDiem, fmtMoney(perDiem)],
    [L.depreciation, fmtMoney(depreciation)],
    ['', ''],
    [L.totalDeductions, fmtMoney(totalDeductions)],
  ]

  autoTable(doc, {
    startY: y,
    head: [],
    body: deductionRows,
    theme: 'plain',
    styles: { font: 'Roboto', fontSize: 10, cellPadding: { top: 2, bottom: 2, left: 4, right: 4 } },
    columnStyles: {
      0: { cellWidth: contentW * 0.65 },
      1: { cellWidth: contentW * 0.35, halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: marginL, right: marginR },
    didParseCell: (data) => {
      if (data.row.index === deductionRows.length - 1) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = [239, 68, 68]
      }
    },
  })

  y = doc.lastAutoTable.finalY + 8

  // Separator
  doc.setDrawColor(200, 200, 200)
  doc.line(marginL, y, pageW - marginR, y)
  y += 8

  // === NET PROFIT ===
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(14)
  const npColor = netProfit >= 0 ? [34, 197, 94] : [239, 68, 68]
  doc.setTextColor(...npColor)
  doc.text(L.netProfit, marginL, y)
  doc.text(fmtMoney(netProfit), pageW - marginR, y, { align: 'right' })
  y += 12

  // === TAX ESTIMATES ===
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(20, 20, 20)
  doc.text(L.taxEstimates, marginL, y)
  y += 2

  const taxRows = [
    [`${L.seTax} (${seTaxRate}%)`, fmtMoney(seTax)],
    [`${L.incomeTax} (${Number(incomeTaxRate).toFixed(1)}%)`, fmtMoney(incomeTax)],
    ['', ''],
    [L.totalTax, fmtMoney(totalTax)],
  ]

  autoTable(doc, {
    startY: y,
    head: [],
    body: taxRows,
    theme: 'plain',
    styles: { font: 'Roboto', fontSize: 10, cellPadding: { top: 2, bottom: 2, left: 4, right: 4 } },
    columnStyles: {
      0: { cellWidth: contentW * 0.65 },
      1: { cellWidth: contentW * 0.35, halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: marginL, right: marginR },
    didParseCell: (data) => {
      if (data.row.index === taxRows.length - 1) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = [245, 158, 11]
      }
    },
  })

  y = doc.lastAutoTable.finalY + 12

  // === DISCLAIMER ===
  doc.setFont('Roboto', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(140, 140, 140)
  const disclaimerLines = doc.splitTextToSize(L.disclaimer, contentW)
  doc.text(disclaimerLines, marginL, y)
  y += disclaimerLines.length * 3.5 + 6

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(160, 160, 160)
  doc.text(L.footer, pageW / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' })

  // Save
  doc.save(`TruckerBook_Tax_Summary_${year}.pdf`)
}


/**
 * Export Tax Summary as Excel with formulas.
 */
export function exportTaxSummaryExcel({
  year, income, expenses, perDiem, depreciation,
  totalExpenses, totalDeductions, netProfit,
  seTax, seTaxRate, incomeTax, incomeTaxRate, totalTax,
  language,
}) {
  const L = getLabels(language || 'en')

  const rows = [
    [L.title],
    [`${L.taxYear}: ${year}`],
    [`${L.generated}: ${new Date().toLocaleDateString('en-US')}`],
    [],
    [L.grossIncome, income],
    [],
    [L.expenses],
  ]

  // Expense rows start at row index 7 (0-based), Excel row 8
  const expStart = rows.length
  for (const e of expenses) {
    rows.push([e.label, e.value])
  }
  const expEnd = rows.length // exclusive
  rows.push([])

  // Total expenses with SUM formula
  const totalExpRow = rows.length
  rows.push([L.totalExpenses, { t: 'n', v: totalExpenses, f: `SUM(B${expStart + 1}:B${expEnd})` }])
  rows.push([])

  rows.push([L.perDiem, perDiem])
  const pdRow = rows.length
  rows.push([L.depreciation, depreciation])
  const depRow = rows.length
  rows.push([])

  // Total deductions = totalExpenses + perDiem + depreciation
  const tdRow = rows.length
  rows.push([L.totalDeductions, { t: 'n', v: totalDeductions, f: `B${totalExpRow + 1}+B${pdRow}+B${depRow}` }])
  rows.push([])

  // Net profit = income - totalDeductions
  const npRow = rows.length
  rows.push([L.netProfit, { t: 'n', v: netProfit, f: `B5-B${tdRow + 1}` }])
  rows.push([])

  rows.push([L.taxEstimates])
  rows.push([`${L.seTax} (${seTaxRate}%)`, { t: 'n', v: seTax, f: `MAX(B${npRow + 1},0)*${seTaxRate / 100}` }])
  const seRow = rows.length
  rows.push([`${L.incomeTax} (${Number(incomeTaxRate).toFixed(1)}%)`, { t: 'n', v: incomeTax, f: `MAX(B${npRow + 1},0)*${incomeTaxRate / 100}` }])
  const itRow = rows.length
  rows.push([])
  rows.push([L.totalTax, { t: 'n', v: totalTax, f: `B${seRow}+B${itRow}` }])

  const ws = XLSX.utils.aoa_to_sheet(rows)

  // Column widths
  ws['!cols'] = [{ wch: 40 }, { wch: 18 }]

  // Number format for money columns
  const range = XLSX.utils.decode_range(ws['!ref'])
  for (let r = range.s.r; r <= range.e.r; r++) {
    const cell = ws[XLSX.utils.encode_cell({ r, c: 1 })]
    if (cell && typeof cell.v === 'number') {
      cell.z = '#,##0.00'
    }
  }

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Tax Summary')
  XLSX.writeFile(wb, `TruckerBook_Tax_Summary_${year}.xlsx`)
}
