/**
 * Tax Summary (Schedule C) — PDF & Excel Export
 * CPA-ready annual tax summary with full IRS 2026 breakdown.
 */
import * as XLSX from 'xlsx'

const FILING_LABELS = {
  en: {
    single: 'Single',
    married_jointly: 'Married Filing Jointly',
    married_separately: 'Married Filing Separately',
    head_of_household: 'Head of Household',
  },
  ru: {
    single: '\u041e\u0434\u0438\u043d\u043e\u043a\u0438\u0439 (Single)',
    married_jointly: '\u0421\u043e\u0432\u043c\u0435\u0441\u0442\u043d\u0430\u044f \u043f\u043e\u0434\u0430\u0447\u0430 (MFJ)',
    married_separately: '\u0420\u0430\u0437\u0434\u0435\u043b\u044c\u043d\u0430\u044f \u043f\u043e\u0434\u0430\u0447\u0430 (MFS)',
    head_of_household: '\u0413\u043b\u0430\u0432\u0430 \u0441\u0435\u043c\u044c\u0438 (HoH)',
  },
  uk: {
    single: '\u041e\u0434\u0438\u043d\u0430\u043a (Single)',
    married_jointly: '\u0421\u043f\u0456\u043b\u044c\u043d\u0430 \u043f\u043e\u0434\u0430\u0447\u0430 (MFJ)',
    married_separately: '\u041e\u043a\u0440\u0435\u043c\u0430 \u043f\u043e\u0434\u0430\u0447\u0430 (MFS)',
    head_of_household: '\u0413\u043e\u043b\u043e\u0432\u0430 \u0441\u0456\u043c\'\u0457 (HoH)',
  },
  es: {
    single: 'Soltero (Single)',
    married_jointly: 'Casado conjunto (MFJ)',
    married_separately: 'Casado por separado (MFS)',
    head_of_household: 'Cabeza de familia (HoH)',
  },
  de: {
    single: 'Alleinstehend (Single)',
    married_jointly: 'Gemeinsame Veranlagung (MFJ)',
    married_separately: 'Getrennte Veranlagung (MFS)',
    head_of_household: 'Haushaltsvorstand (HoH)',
  },
  fr: {
    single: 'C\u00e9libataire (Single)',
    married_jointly: 'Mari\u00e9s conjointe (MFJ)',
    married_separately: 'Mari\u00e9s s\u00e9par\u00e9e (MFS)',
    head_of_household: 'Chef de famille (HoH)',
  },
  tr: {
    single: 'Bekar (Single)',
    married_jointly: 'Evli ortak beyan (MFJ)',
    married_separately: 'Evli ayr\u0131 beyan (MFS)',
    head_of_household: 'Hane reisi (HoH)',
  },
  pl: {
    single: 'Osoba samotna (Single)',
    married_jointly: 'Wsp\u00f3lne rozliczenie (MFJ)',
    married_separately: 'Oddzielne rozliczenie (MFS)',
    head_of_household: 'G\u0142owa rodziny (HoH)',
  },
}

const PDF_LABELS = {
  en: {
    title: 'TruckerBook \u2014 Annual Tax Summary',
    subtitle: 'IRS Schedule C \u2014 Profit or Loss from Business',
    taxYear: 'Tax Year',
    generated: 'Generated',
    filingStatus: 'Filing Status',
    grossIncome: 'GROSS INCOME',
    expenses: 'BUSINESS EXPENSES (Schedule C)',
    fuel: 'Fuel',
    repairs: 'Repairs & Maintenance',
    insurance: 'Insurance',
    lease: 'Truck Payments / Lease',
    tolls: 'Tolls',
    parking: 'Parking',
    otherExpenses: 'Other Expenses',
    totalExpenses: 'TOTAL EXPENSES',
    perDiem: 'Per Diem Deduction',
    depreciation: 'Truck Depreciation',
    totalDeductions: 'TOTAL DEDUCTIONS',
    netProfit: 'NET PROFIT (Loss)',
    seTaxBreakdown: 'SELF-EMPLOYMENT TAX (Schedule SE, 2026)',
    seEarnings: 'SE earnings (net profit \u00d7 92.35%)',
    ssTax: 'Social Security (12.4%, capped at $184,500)',
    medicareTax: 'Medicare (2.9%)',
    additionalMedicare: 'Additional Medicare (0.9% over threshold)',
    totalSeTax: 'TOTAL SE TAX',
    deductibleHalfSE: 'Deductible \u00bd of SE tax (SS + Medicare)',
    agi: 'Adjusted Gross Income (AGI)',
    standardDeduction: 'Standard Deduction',
    taxableIncome: 'Taxable Income',
    incomeTax: 'Federal Income Tax (progressive, 2026)',
    totalTax: 'TOTAL ESTIMATED TAX',
    disclaimer: 'Generated by TruckerBook for informational purposes only. 2026 IRS standard deductions and tax brackets are applied. NOT included: state income tax, itemized deductions, AMT, Net Investment Income Tax, tax credits (Child Tax Credit, EITC, etc.). Consult a licensed CPA or EA for the final return.',
    footer: 'Generated by TruckerBook | truckerbook-app.vercel.app',
    page: 'Page',
  },
  ru: {
    title: 'TruckerBook \u2014 \u0413\u043e\u0434\u043e\u0432\u043e\u0439 \u043d\u0430\u043b\u043e\u0433\u043e\u0432\u044b\u0439 \u043e\u0442\u0447\u0451\u0442',
    subtitle: 'IRS Schedule C \u2014 \u041f\u0440\u0438\u0431\u044b\u043b\u044c / \u0443\u0431\u044b\u0442\u043e\u043a \u043e\u0442 \u0431\u0438\u0437\u043d\u0435\u0441\u0430',
    taxYear: '\u041d\u0430\u043b\u043e\u0433\u043e\u0432\u044b\u0439 \u0433\u043e\u0434',
    generated: '\u0421\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d',
    filingStatus: '\u0421\u0442\u0430\u0442\u0443\u0441 \u043f\u043e\u0434\u0430\u0447\u0438',
    grossIncome: '\u0412\u0410\u041b\u041e\u0412\u042b\u0419 \u0414\u041e\u0425\u041e\u0414',
    expenses: '\u0420\u0410\u0421\u0425\u041e\u0414\u042b (Schedule C)',
    fuel: '\u0422\u043e\u043f\u043b\u0438\u0432\u043e',
    repairs: '\u0420\u0435\u043c\u043e\u043d\u0442 \u0438 \u0422\u041e',
    insurance: '\u0421\u0442\u0440\u0430\u0445\u043e\u0432\u0430\u043d\u0438\u0435',
    lease: '\u041f\u043b\u0430\u0442\u0435\u0436\u0438 \u0437\u0430 \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442 / \u041b\u0438\u0437\u0438\u043d\u0433',
    tolls: '\u041f\u043b\u0430\u0442\u043d\u044b\u0435 \u0434\u043e\u0440\u043e\u0433\u0438',
    parking: '\u041f\u0430\u0440\u043a\u043e\u0432\u043a\u0430',
    otherExpenses: '\u041f\u0440\u043e\u0447\u0438\u0435 \u0440\u0430\u0441\u0445\u043e\u0434\u044b',
    totalExpenses: '\u0418\u0422\u041e\u0413\u041e \u0420\u0410\u0421\u0425\u041e\u0414\u042b',
    perDiem: '\u0412\u044b\u0447\u0435\u0442 Per Diem',
    depreciation: '\u0410\u043c\u043e\u0440\u0442\u0438\u0437\u0430\u0446\u0438\u044f \u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u0430',
    totalDeductions: '\u0412\u0421\u0415\u0413\u041e \u0412\u042b\u0427\u0415\u0422\u042b',
    netProfit: '\u0427\u0418\u0421\u0422\u0410\u042f \u041f\u0420\u0418\u0411\u042b\u041b\u042c (\u0423\u0431\u044b\u0442\u043e\u043a)',
    seTaxBreakdown: '\u041d\u0410\u041b\u041e\u0413 SELF-EMPLOYMENT (Schedule SE, 2026)',
    seEarnings: 'SE \u0434\u043e\u0445\u043e\u0434 (\u0447\u0438\u0441\u0442\u0430\u044f \u043f\u0440\u0438\u0431\u044b\u043b\u044c \u00d7 92.35%)',
    ssTax: 'Social Security (12.4%, \u043a\u0430\u043f $184,500)',
    medicareTax: 'Medicare (2.9%)',
    additionalMedicare: 'Additional Medicare (0.9% \u0441\u0432\u0435\u0440\u0445 \u043f\u043e\u0440\u043e\u0433\u0430)',
    totalSeTax: '\u0418\u0422\u041e\u0413\u041e SE \u043d\u0430\u043b\u043e\u0433',
    deductibleHalfSE: '\u0412\u044b\u0447\u0435\u0442 \u00bd SE \u043d\u0430\u043b\u043e\u0433\u0430 (SS + Medicare)',
    agi: 'AGI \u2014 \u0441\u043a\u043e\u0440\u0440\u0435\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u0434\u043e\u0445\u043e\u0434',
    standardDeduction: '\u0421\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u043d\u044b\u0439 \u0432\u044b\u0447\u0435\u0442',
    taxableIncome: '\u041d\u0430\u043b\u043e\u0433\u043e\u043e\u0431\u043b\u0430\u0433\u0430\u0435\u043c\u044b\u0439 \u0434\u043e\u0445\u043e\u0434',
    incomeTax: '\u0424\u0435\u0434\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u0439 \u043f\u043e\u0434\u043e\u0445\u043e\u0434\u043d\u044b\u0439 (\u043f\u0440\u043e\u0433\u0440\u0435\u0441\u0441\u0438\u0432\u043d\u043e, 2026)',
    totalTax: '\u0418\u0422\u041e\u0413\u041e \u041d\u0410\u041b\u041e\u0413',
    disclaimer: '\u041e\u0442\u0447\u0451\u0442 \u0441\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d TruckerBook \u0432 \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0445 \u0446\u0435\u043b\u044f\u0445. \u041f\u0440\u0438\u043c\u0435\u043d\u0435\u043d\u044b \u0441\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u043d\u044b\u0439 \u0432\u044b\u0447\u0435\u0442 \u0438 \u0431\u0440\u0435\u043a\u0435\u0442\u044b IRS 2026 \u0433\u043e\u0434\u0430. \u041d\u0415 \u0432\u043a\u043b\u044e\u0447\u0435\u043d\u043e: state income tax, itemized deductions, AMT, Net Investment Income Tax, tax credits (CTC, EITC \u0438 \u0434\u0440.). \u0414\u043b\u044f \u0442\u043e\u0447\u043d\u043e\u0439 \u0434\u0435\u043a\u043b\u0430\u0440\u0430\u0446\u0438\u0438 \u043e\u0431\u0440\u0430\u0442\u0438\u0442\u0435\u0441\u044c \u043a CPA \u0438\u043b\u0438 EA.',
    footer: '\u0421\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u043e TruckerBook | truckerbook-app.vercel.app',
    page: '\u0421\u0442\u0440.',
  },
  uk: {
    title: 'TruckerBook \u2014 \u0420\u0456\u0447\u043d\u0438\u0439 \u043f\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0438\u0439 \u0437\u0432\u0456\u0442',
    subtitle: 'IRS Schedule C \u2014 \u041f\u0440\u0438\u0431\u0443\u0442\u043e\u043a / \u0437\u0431\u0438\u0442\u043e\u043a \u0432\u0456\u0434 \u0431\u0456\u0437\u043d\u0435\u0441\u0443',
    taxYear: '\u041f\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0438\u0439 \u0440\u0456\u043a',
    generated: '\u0421\u0444\u043e\u0440\u043c\u043e\u0432\u0430\u043d\u043e',
    filingStatus: '\u0421\u0442\u0430\u0442\u0443\u0441 \u043f\u043e\u0434\u0430\u0447\u0456',
    grossIncome: '\u0412\u0410\u041b\u041e\u0412\u0418\u0419 \u0414\u041e\u0425\u0406\u0414',
    expenses: '\u0412\u0418\u0422\u0420\u0410\u0422\u0418 (Schedule C)',
    fuel: '\u041f\u0430\u043b\u0438\u0432\u043e',
    repairs: '\u0420\u0435\u043c\u043e\u043d\u0442 \u0456 \u0422\u041e',
    insurance: '\u0421\u0442\u0440\u0430\u0445\u0443\u0432\u0430\u043d\u043d\u044f',
    lease: '\u041f\u043b\u0430\u0442\u0435\u0436\u0456 / \u041b\u0456\u0437\u0438\u043d\u0433',
    tolls: '\u041f\u043b\u0430\u0442\u043d\u0456 \u0434\u043e\u0440\u043e\u0433\u0438',
    parking: '\u041f\u0430\u0440\u043a\u0443\u0432\u0430\u043d\u043d\u044f',
    otherExpenses: '\u0406\u043d\u0448\u0456 \u0432\u0438\u0442\u0440\u0430\u0442\u0438',
    totalExpenses: '\u0412\u0421\u042c\u041e\u0413\u041e \u0412\u0418\u0422\u0420\u0410\u0422',
    perDiem: '\u0412\u0438\u0440\u0430\u0445\u0443\u0432\u0430\u043d\u043d\u044f Per Diem',
    depreciation: '\u0410\u043c\u043e\u0440\u0442\u0438\u0437\u0430\u0446\u0456\u044f',
    totalDeductions: '\u0412\u0421\u042c\u041e\u0413\u041e \u0412\u0418\u0420\u0410\u0425\u0423\u0412\u0410\u041d\u042c',
    netProfit: '\u0427\u0418\u0421\u0422\u0418\u0419 \u041f\u0420\u0418\u0411\u0423\u0422\u041e\u041a',
    seTaxBreakdown: '\u041f\u041e\u0414\u0410\u0422\u041e\u041a SELF-EMPLOYMENT (SE, 2026)',
    seEarnings: 'SE \u0434\u043e\u0445\u0456\u0434 (\u0447\u0438\u0441\u0442\u0438\u0439 \u043f\u0440\u0438\u0431\u0443\u0442\u043e\u043a \u00d7 92.35%)',
    ssTax: 'Social Security (12.4%, \u043b\u0456\u043c\u0456\u0442 $184,500)',
    medicareTax: 'Medicare (2.9%)',
    additionalMedicare: 'Additional Medicare (0.9% \u043f\u043e\u043d\u0430\u0434 \u043f\u043e\u0440\u0456\u0433)',
    totalSeTax: '\u0412\u0421\u042c\u041e\u0413\u041e SE \u043f\u043e\u0434\u0430\u0442\u043e\u043a',
    deductibleHalfSE: '\u0412\u0438\u0440\u0430\u0445\u0443\u0432\u0430\u043d\u043d\u044f \u00bd SE (SS + Medicare)',
    agi: 'AGI \u2014 \u0441\u043a\u043e\u0440\u0438\u0433\u043e\u0432\u0430\u043d\u0438\u0439 \u0434\u043e\u0445\u0456\u0434',
    standardDeduction: '\u0421\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u043d\u0435 \u0432\u0438\u0440\u0430\u0445\u0443\u0432\u0430\u043d\u043d\u044f',
    taxableIncome: '\u041e\u043f\u043e\u0434\u0430\u0442\u043a\u043e\u0432\u0443\u0432\u0430\u043d\u0438\u0439 \u0434\u043e\u0445\u0456\u0434',
    incomeTax: '\u0424\u0435\u0434\u0435\u0440\u0430\u043b\u044c\u043d\u0438\u0439 \u043f\u0440\u0438\u0431\u0443\u0442\u043a\u043e\u0432\u0438\u0439 (2026)',
    totalTax: '\u0412\u0421\u042c\u041e\u0413\u041e \u041f\u041e\u0414\u0410\u0422\u041e\u041a',
    disclaimer: '\u0417\u0432\u0456\u0442 \u0441\u0444\u043e\u0440\u043c\u043e\u0432\u0430\u043d\u043e TruckerBook \u0432 \u0456\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0456\u0439\u043d\u0438\u0445 \u0446\u0456\u043b\u044f\u0445. \u0417\u0430\u0441\u0442\u043e\u0441\u043e\u0432\u0430\u043d\u0456 \u0441\u0442\u0430\u043d\u0434\u0430\u0440\u0442\u043d\u0435 \u0432\u0438\u0440\u0430\u0445\u0443\u0432\u0430\u043d\u043d\u044f \u0442\u0430 \u0431\u0440\u0435\u043a\u0435\u0442\u0438 IRS 2026 \u0440\u043e\u043a\u0443. \u041d\u0415 \u0432\u043a\u043b\u044e\u0447\u0435\u043d\u043e: state income tax, itemized deductions, AMT, NIIT, tax credits. \u0414\u043b\u044f \u0442\u043e\u0447\u043d\u043e\u0457 \u0434\u0435\u043a\u043b\u0430\u0440\u0430\u0446\u0456\u0457 \u0437\u0432\u0435\u0440\u043d\u0456\u0442\u044c\u0441\u044f \u0434\u043e CPA \u0430\u0431\u043e EA.',
    footer: '\u0421\u0444\u043e\u0440\u043c\u043e\u0432\u0430\u043d\u043e TruckerBook | truckerbook-app.vercel.app',
    page: '\u0421\u0442\u043e\u0440.',
  },
  es: {
    title: 'TruckerBook \u2014 Resumen Fiscal Anual',
    subtitle: 'IRS Schedule C \u2014 Ganancias o P\u00e9rdidas del Negocio',
    taxYear: 'A\u00f1o Fiscal',
    generated: 'Generado',
    filingStatus: 'Estado civil',
    grossIncome: 'INGRESO BRUTO',
    expenses: 'GASTOS DE NEGOCIO (Schedule C)',
    fuel: 'Combustible',
    repairs: 'Reparaciones y Mantenimiento',
    insurance: 'Seguro',
    lease: 'Pagos del cami\u00f3n / Leasing',
    tolls: 'Peajes',
    parking: 'Estacionamiento',
    otherExpenses: 'Otros gastos',
    totalExpenses: 'TOTAL GASTOS',
    perDiem: 'Deducci\u00f3n Per Diem',
    depreciation: 'Depreciaci\u00f3n del cami\u00f3n',
    totalDeductions: 'TOTAL DEDUCCIONES',
    netProfit: 'GANANCIA NETA',
    seTaxBreakdown: 'IMPUESTO DE AUTOEMPLEO (Schedule SE, 2026)',
    seEarnings: 'Ingreso SE (ganancia neta \u00d7 92.35%)',
    ssTax: 'Seguro Social (12.4%, tope $184,500)',
    medicareTax: 'Medicare (2.9%)',
    additionalMedicare: 'Medicare Adicional (0.9% sobre umbral)',
    totalSeTax: 'TOTAL IMPUESTO SE',
    deductibleHalfSE: 'Deducci\u00f3n \u00bd SE (SS + Medicare)',
    agi: 'Ingreso Bruto Ajustado (AGI)',
    standardDeduction: 'Deducci\u00f3n Est\u00e1ndar',
    taxableIncome: 'Ingreso Gravable',
    incomeTax: 'Impuesto Federal (progresivo, 2026)',
    totalTax: 'TOTAL IMPUESTO',
    disclaimer: 'Generado por TruckerBook con fines informativos. Aplicadas deducci\u00f3n est\u00e1ndar y tramos IRS 2026. NO incluye: impuesto estatal, deducciones detalladas, AMT, NIIT, cr\u00e9ditos fiscales. Consulte a un CPA o EA autorizado.',
    footer: 'Generado por TruckerBook | truckerbook-app.vercel.app',
    page: 'P\u00e1g.',
  },
  de: {
    title: 'TruckerBook \u2014 J\u00e4hrliche Steuer\u00fcbersicht',
    subtitle: 'IRS Schedule C \u2014 Gewinn oder Verlust aus Gesch\u00e4ftst\u00e4tigkeit',
    taxYear: 'Steuerjahr',
    generated: 'Erstellt',
    filingStatus: 'Veranlagungsart',
    grossIncome: 'BRUTTOEINKOMMEN',
    expenses: 'BETRIEBSAUSGABEN (Schedule C)',
    fuel: 'Kraftstoff',
    repairs: 'Reparaturen & Wartung',
    insurance: 'Versicherung',
    lease: 'LKW-Zahlungen / Leasing',
    tolls: 'Mautgeb\u00fchren',
    parking: 'Parken',
    otherExpenses: 'Sonstige Ausgaben',
    totalExpenses: 'AUSGABEN GESAMT',
    perDiem: 'Per Diem Abzug',
    depreciation: 'LKW-Abschreibung',
    totalDeductions: 'ABZ\u00dcGE GESAMT',
    netProfit: 'NETTOGEWINN',
    seTaxBreakdown: 'SELBSTST\u00c4NDIGENSTEUER (SE, 2026)',
    seEarnings: 'SE-Einkommen (Netto \u00d7 92,35%)',
    ssTax: 'Social Security (12,4%, Cap $184.500)',
    medicareTax: 'Medicare (2,9%)',
    additionalMedicare: 'Additional Medicare (0,9% \u00fcber Grenze)',
    totalSeTax: 'SE-STEUER GESAMT',
    deductibleHalfSE: 'Abzug \u00bd SE (SS + Medicare)',
    agi: 'Bereinigtes Bruttoeinkommen (AGI)',
    standardDeduction: 'Standardabzug',
    taxableIncome: 'Zu versteuerndes Einkommen',
    incomeTax: 'Bundeseinkommensteuer (progressiv, 2026)',
    totalTax: 'STEUER GESAMT',
    disclaimer: 'Erstellt von TruckerBook zu Informationszwecken. Standardabzug und IRS 2026 Klassen angewendet. NICHT enthalten: Staatssteuer, Einzelabz\u00fcge, AMT, NIIT, Steuergutschriften. Konsultieren Sie einen CPA/EA.',
    footer: 'Erstellt von TruckerBook | truckerbook-app.vercel.app',
    page: 'Seite',
  },
  fr: {
    title: 'TruckerBook \u2014 R\u00e9sum\u00e9 Fiscal Annuel',
    subtitle: 'IRS Schedule C \u2014 B\u00e9n\u00e9fice ou Perte d\u2019Entreprise',
    taxYear: 'Ann\u00e9e fiscale',
    generated: 'G\u00e9n\u00e9r\u00e9',
    filingStatus: 'Statut de d\u00e9p\u00f4t',
    grossIncome: 'REVENU BRUT',
    expenses: 'D\u00c9PENSES D\u2019ENTREPRISE (Schedule C)',
    fuel: 'Carburant',
    repairs: 'R\u00e9parations & Entretien',
    insurance: 'Assurance',
    lease: 'Paiements camion / Leasing',
    tolls: 'P\u00e9ages',
    parking: 'Stationnement',
    otherExpenses: 'Autres d\u00e9penses',
    totalExpenses: 'TOTAL D\u00c9PENSES',
    perDiem: 'D\u00e9duction Per Diem',
    depreciation: 'Amortissement',
    totalDeductions: 'TOTAL D\u00c9DUCTIONS',
    netProfit: 'B\u00c9N\u00c9FICE NET',
    seTaxBreakdown: 'IMP\u00d4T TRAVAILLEUR IND\u00c9PENDANT (SE, 2026)',
    seEarnings: 'Revenu SE (b\u00e9n\u00e9fice net \u00d7 92,35%)',
    ssTax: 'S\u00e9curit\u00e9 Sociale (12,4%, plafond 184 500$)',
    medicareTax: 'Medicare (2,9%)',
    additionalMedicare: 'Medicare additionnel (0,9% au-dessus)',
    totalSeTax: 'TOTAL IMP\u00d4T SE',
    deductibleHalfSE: 'D\u00e9duction \u00bd SE (SS + Medicare)',
    agi: 'Revenu Brut Ajust\u00e9 (AGI)',
    standardDeduction: 'D\u00e9duction standard',
    taxableIncome: 'Revenu imposable',
    incomeTax: 'Imp\u00f4t f\u00e9d\u00e9ral (progressif, 2026)',
    totalTax: 'TOTAL IMP\u00d4T',
    disclaimer: 'G\u00e9n\u00e9r\u00e9 par TruckerBook \u00e0 titre informatif. D\u00e9duction standard et tranches IRS 2026 appliqu\u00e9es. NON inclus: imp\u00f4t d\u2019\u00c9tat, d\u00e9ductions d\u00e9taill\u00e9es, AMT, NIIT, cr\u00e9dits. Consultez un CPA/EA.',
    footer: 'G\u00e9n\u00e9r\u00e9 par TruckerBook | truckerbook-app.vercel.app',
    page: 'Page',
  },
  tr: {
    title: 'TruckerBook \u2014 Y\u0131ll\u0131k Vergi \u00d6zeti',
    subtitle: 'IRS Schedule C \u2014 \u0130\u015f Kar\u0131 veya Zarar\u0131',
    taxYear: 'Vergi Y\u0131l\u0131',
    generated: 'Olu\u015fturuldu',
    filingStatus: 'Beyan durumu',
    grossIncome: 'BR\u00dcT GEL\u0130R',
    expenses: '\u0130\u015e G\u0130DERLER\u0130 (Schedule C)',
    fuel: 'Yak\u0131t',
    repairs: 'Onar\u0131m & Bak\u0131m',
    insurance: 'Sigorta',
    lease: 'Kamyon \u00f6demeleri / Leasing',
    tolls: 'Ge\u00e7i\u015f \u00fccretleri',
    parking: 'Otopark',
    otherExpenses: 'Di\u011fer giderler',
    totalExpenses: 'TOPLAM G\u0130DERLER',
    perDiem: 'Per Diem kesintisi',
    depreciation: 'Amortisman',
    totalDeductions: 'TOPLAM KES\u0130NT\u0130LER',
    netProfit: 'NET KAR',
    seTaxBreakdown: 'SERBEST MESLEK VERG\u0130S\u0130 (SE, 2026)',
    seEarnings: 'SE kazanc\u0131 (net kar \u00d7 92,35%)',
    ssTax: 'Sosyal G\u00fcvenlik (%12,4, tavan $184.500)',
    medicareTax: 'Medicare (%2,9)',
    additionalMedicare: 'Ek Medicare (%0,9 e\u015fi\u011fin \u00fcst\u00fc)',
    totalSeTax: 'TOPLAM SE VERG\u0130S\u0130',
    deductibleHalfSE: 'Kesinti \u00bd SE (SS + Medicare)',
    agi: 'D\u00fczeltilmi\u015f Br\u00fct Gelir (AGI)',
    standardDeduction: 'Standart kesinti',
    taxableIncome: 'Vergilendirilebilir gelir',
    incomeTax: 'Federal gelir vergisi (artan oranl\u0131, 2026)',
    totalTax: 'TOPLAM VERG\u0130',
    disclaimer: 'TruckerBook taraf\u0131ndan bilgi ama\u00e7l\u0131 olu\u015fturuldu. 2026 IRS standart kesintisi ve dilimleri uyguland\u0131. Dahil DE\u011e\u0130L: eyalet vergisi, detayl\u0131 kesintiler, AMT, NIIT, vergi kredileri. Lisansl\u0131 bir CPA/EA ile do\u011frulay\u0131n.',
    footer: 'TruckerBook taraf\u0131ndan olu\u015fturuldu | truckerbook-app.vercel.app',
    page: 'Sayfa',
  },
  pl: {
    title: 'TruckerBook \u2014 Roczne Podsumowanie Podatkowe',
    subtitle: 'IRS Schedule C \u2014 Zysk lub Strata z Dzia\u0142alno\u015bci',
    taxYear: 'Rok podatkowy',
    generated: 'Wygenerowano',
    filingStatus: 'Status rozliczenia',
    grossIncome: 'DOCH\u00d3D BRUTTO',
    expenses: 'WYDATKI BIZNESOWE (Schedule C)',
    fuel: 'Paliwo',
    repairs: 'Naprawy i konserwacja',
    insurance: 'Ubezpieczenie',
    lease: 'P\u0142atno\u015bci za ci\u0119\u017car\u00f3wk\u0119 / Leasing',
    tolls: 'Op\u0142aty drogowe',
    parking: 'Parking',
    otherExpenses: 'Inne wydatki',
    totalExpenses: 'RAZEM WYDATKI',
    perDiem: 'Odliczenie Per Diem',
    depreciation: 'Amortyzacja',
    totalDeductions: 'RAZEM ODLICZENIA',
    netProfit: 'ZYSK NETTO',
    seTaxBreakdown: 'PODATEK OD SAMOZATRUDNIENIA (SE, 2026)',
    seEarnings: 'Doch\u00f3d SE (zysk netto \u00d7 92,35%)',
    ssTax: 'Social Security (12,4%, cap $184,500)',
    medicareTax: 'Medicare (2,9%)',
    additionalMedicare: 'Dodatkowe Medicare (0,9% ponad pr\u00f3g)',
    totalSeTax: 'RAZEM PODATEK SE',
    deductibleHalfSE: 'Odliczenie \u00bd SE (SS + Medicare)',
    agi: 'Skorygowany doch\u00f3d brutto (AGI)',
    standardDeduction: 'Odliczenie standardowe',
    taxableIncome: 'Doch\u00f3d do opodatkowania',
    incomeTax: 'Federalny podatek dochodowy (progresywny, 2026)',
    totalTax: 'RAZEM PODATEK',
    disclaimer: 'Wygenerowano przez TruckerBook w celach informacyjnych. Zastosowano standardowe odliczenie i progi IRS 2026. NIE uwzgl\u0119dniono: podatku stanowego, odlicze\u0144 szczeg\u00f3\u0142owych, AMT, NIIT, kredyt\u00f3w podatkowych. Skonsultuj si\u0119 z CPA/EA.',
    footer: 'Wygenerowano przez TruckerBook | truckerbook-app.vercel.app',
    page: 'Str.',
  },
}

function getLabels(lang) {
  return PDF_LABELS[lang] || PDF_LABELS.en
}

function getFilingLabel(lang, status) {
  const langMap = FILING_LABELS[lang] || FILING_LABELS.en
  return langMap[status] || FILING_LABELS.en[status] || status
}

function fmtMoney(n) {
  if (n == null) return '\u2014'
  const abs = Math.abs(Number(n) || 0).toFixed(2)
  return n < 0 ? '-$' + abs : '$' + abs
}

/**
 * Generate and download a professional Tax Summary PDF with full breakdown.
 */
export async function generateTaxSummaryPdf({
  year, income, expenses, perDiem, depreciation,
  totalExpenses, totalDeductions,
  breakdown,
  language, companyName,
}) {
  const { default: jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')
  const { robotoRegularBase64, robotoBoldBase64 } = await import('./roboto-font.js')

  const lang = language || 'en'
  const L = getLabels(lang)
  const filingLabel = getFilingLabel(lang, breakdown.filingStatus)

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // Embed Roboto for Cyrillic
  doc.addFileToVFS('Roboto-Regular.ttf', robotoRegularBase64)
  doc.addFont('Roboto-Regular.ttf', 'Roboto', 'normal')
  doc.addFileToVFS('Roboto-Bold.ttf', robotoBoldBase64)
  doc.addFont('Roboto-Bold.ttf', 'Roboto', 'bold')
  doc.setFont('Roboto', 'normal')

  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const marginL = 14
  const marginR = 14
  const contentW = pageW - marginL - marginR

  let y = 16

  doc.setFillColor(245, 158, 11)
  doc.rect(marginL, y - 2, contentW, 1, 'F')
  y += 6

  // Title
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(20, 20, 20)
  doc.text(L.title, marginL, y)
  y += 7

  doc.setFont('Roboto', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(L.subtitle, marginL, y)
  y += 8

  if (companyName) {
    doc.text(companyName, marginL, y)
    y += 5
  }
  doc.setFontSize(10)
  doc.setTextColor(60, 60, 60)
  doc.text(`${L.taxYear}: ${year}`, marginL, y)
  doc.text(`${L.generated}: ${new Date().toLocaleDateString('en-US')}`, pageW - marginR, y, { align: 'right' })
  y += 5
  doc.text(`${L.filingStatus}: ${filingLabel}`, marginL, y)
  y += 6

  doc.setDrawColor(200, 200, 200)
  doc.line(marginL, y, pageW - marginR, y)
  y += 7

  // GROSS INCOME
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(34, 197, 94)
  doc.text(L.grossIncome, marginL, y)
  doc.text(fmtMoney(income), pageW - marginR, y, { align: 'right' })
  y += 9

  // EXPENSES
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(20, 20, 20)
  doc.text(L.expenses, marginL, y)
  y += 2

  const expenseRows = expenses.map(e => [e.label, fmtMoney(e.value)])
  expenseRows.push(['', ''])
  expenseRows.push([L.totalExpenses, fmtMoney(totalExpenses)])

  autoTable(doc, {
    startY: y,
    head: [],
    body: expenseRows,
    theme: 'plain',
    styles: { font: 'Roboto', fontSize: 10, cellPadding: { top: 2, bottom: 2, left: 4, right: 4 } },
    columnStyles: {
      0: { cellWidth: contentW * 0.65 },
      1: { cellWidth: contentW * 0.35, halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: marginL, right: marginR },
    didParseCell: (data) => {
      if (data.row.index === expenseRows.length - 1) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = [239, 68, 68]
      }
    },
  })
  y = doc.lastAutoTable.finalY + 6

  // Per Diem + Depreciation + Total Deductions
  const deductionRows = [
    [L.perDiem, fmtMoney(perDiem)],
    [L.depreciation, fmtMoney(depreciation)],
    ['', ''],
    [L.totalDeductions, fmtMoney(totalDeductions)],
  ]
  autoTable(doc, {
    startY: y,
    head: [],
    body: deductionRows,
    theme: 'plain',
    styles: { font: 'Roboto', fontSize: 10, cellPadding: { top: 2, bottom: 2, left: 4, right: 4 } },
    columnStyles: {
      0: { cellWidth: contentW * 0.65 },
      1: { cellWidth: contentW * 0.35, halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: marginL, right: marginR },
    didParseCell: (data) => {
      if (data.row.index === deductionRows.length - 1) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = [239, 68, 68]
      }
    },
  })
  y = doc.lastAutoTable.finalY + 6

  doc.setDrawColor(200, 200, 200)
  doc.line(marginL, y, pageW - marginR, y)
  y += 7

  // NET PROFIT
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(13)
  const npColor = breakdown.netProfit >= 0 ? [34, 197, 94] : [239, 68, 68]
  doc.setTextColor(...npColor)
  doc.text(L.netProfit, marginL, y)
  doc.text(fmtMoney(breakdown.netProfit), pageW - marginR, y, { align: 'right' })
  y += 10

  // Page break check
  if (y > pageH - 80) {
    doc.addPage()
    y = 16
  }

  // SE TAX BREAKDOWN
  doc.setFont('Roboto', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(20, 20, 20)
  doc.text(L.seTaxBreakdown, marginL, y)
  y += 2

  const seRows = [
    [L.seEarnings, fmtMoney(breakdown.taxableSEIncome)],
    [L.ssTax, fmtMoney(breakdown.ssTax)],
    [L.medicareTax, fmtMoney(breakdown.medicareTax)],
    [L.additionalMedicare, fmtMoney(breakdown.additionalMedicare)],
    ['', ''],
    [L.totalSeTax, fmtMoney(breakdown.seTax)],
  ]
  autoTable(doc, {
    startY: y,
    head: [],
    body: seRows,
    theme: 'plain',
    styles: { font: 'Roboto', fontSize: 10, cellPadding: { top: 2, bottom: 2, left: 4, right: 4 } },
    columnStyles: {
      0: { cellWidth: contentW * 0.65 },
      1: { cellWidth: contentW * 0.35, halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: marginL, right: marginR },
    didParseCell: (data) => {
      if (data.row.index === seRows.length - 1) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = [245, 158, 11]
      }
    },
  })
  y = doc.lastAutoTable.finalY + 6

  // Page break check
  if (y > pageH - 70) {
    doc.addPage()
    y = 16
  }

  // AGI / Standard Deduction / Taxable Income
  const agiRows = [
    [L.deductibleHalfSE, fmtMoney(breakdown.deductibleHalfSE)],
    [L.agi, fmtMoney(breakdown.agi)],
    [L.standardDeduction, fmtMoney(breakdown.standardDeduction)],
    ['', ''],
    [L.taxableIncome, fmtMoney(breakdown.taxableIncome)],
  ]
  autoTable(doc, {
    startY: y,
    head: [],
    body: agiRows,
    theme: 'plain',
    styles: { font: 'Roboto', fontSize: 10, cellPadding: { top: 2, bottom: 2, left: 4, right: 4 } },
    columnStyles: {
      0: { cellWidth: contentW * 0.65 },
      1: { cellWidth: contentW * 0.35, halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: marginL, right: marginR },
    didParseCell: (data) => {
      if (data.row.index === agiRows.length - 1) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = [20, 20, 20]
      }
    },
  })
  y = doc.lastAutoTable.finalY + 6

  // Income Tax + Total
  const taxRows = [
    [`${L.incomeTax} (${Number(breakdown.effectiveRate).toFixed(1)}%)`, fmtMoney(breakdown.incomeTax)],
    ['', ''],
    [L.totalTax, fmtMoney(breakdown.totalTax)],
  ]
  autoTable(doc, {
    startY: y,
    head: [],
    body: taxRows,
    theme: 'plain',
    styles: { font: 'Roboto', fontSize: 10, cellPadding: { top: 2, bottom: 2, left: 4, right: 4 } },
    columnStyles: {
      0: { cellWidth: contentW * 0.65 },
      1: { cellWidth: contentW * 0.35, halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: marginL, right: marginR },
    didParseCell: (data) => {
      if (data.row.index === taxRows.length - 1) {
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.fontSize = 12
        data.cell.styles.textColor = [245, 158, 11]
      }
    },
  })
  y = doc.lastAutoTable.finalY + 10

  if (y > pageH - 40) {
    doc.addPage()
    y = 16
  }

  // DISCLAIMER
  doc.setFont('Roboto', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(140, 140, 140)
  const disclaimerLines = doc.splitTextToSize(L.disclaimer, contentW)
  doc.text(disclaimerLines, marginL, y)

  doc.setFontSize(8)
  doc.setTextColor(160, 160, 160)
  doc.text(L.footer, pageW / 2, pageH - 10, { align: 'center' })

  doc.save(`TruckerBook_Tax_Summary_${year}.pdf`)
}


/**
 * Export Tax Summary as Excel with formulas — every number traceable.
 * All tax calculations use Excel formulas so the accountant can verify / edit.
 */
export function exportTaxSummaryExcel({
  year, income, expenses, perDiem, depreciation,
  totalExpenses, totalDeductions,
  breakdown,
  language,
}) {
  const L = getLabels(language || 'en')
  const filingLabel = getFilingLabel(language || 'en', breakdown.filingStatus)

  // Constants by filing status (used in formulas)
  const STANDARD_DEDUCTIONS = {
    single: 16100,
    married_jointly: 32200,
    married_separately: 16100,
    head_of_household: 24150,
  }
  const ADDITIONAL_MEDICARE_THRESHOLDS = {
    single: 200000,
    married_jointly: 250000,
    married_separately: 125000,
    head_of_household: 200000,
  }
  const BRACKETS = {
    single:             [[12400,0.10],[50400,0.12],[105700,0.22],[201775,0.24],[256225,0.32],[640600,0.35]],
    married_jointly:    [[24800,0.10],[100800,0.12],[211400,0.22],[403550,0.24],[512450,0.32],[768700,0.35]],
    married_separately: [[12400,0.10],[50400,0.12],[105700,0.22],[201775,0.24],[256225,0.32],[384350,0.35]],
    head_of_household:  [[17700,0.10],[67450,0.12],[105700,0.22],[201750,0.24],[256200,0.32],[640600,0.35]],
  }
  const topRate = 0.37

  const stdDed = STANDARD_DEDUCTIONS[breakdown.filingStatus] || STANDARD_DEDUCTIONS.single
  const addlThreshold = ADDITIONAL_MEDICARE_THRESHOLDS[breakdown.filingStatus] || 200000
  const brackets = BRACKETS[breakdown.filingStatus] || BRACKETS.single

  const rows = []
  // Row 1..4: header
  rows.push([L.title])
  rows.push([`${L.taxYear}: ${year}`])
  rows.push([`${L.filingStatus}: ${filingLabel}`])
  rows.push([`${L.generated}: ${new Date().toLocaleDateString('en-US')}`])
  rows.push([])

  // Row 6: Gross income
  const incomeRow = rows.length + 1
  rows.push([L.grossIncome, income])
  rows.push([])

  // Expenses header
  rows.push([L.expenses])
  const expStart = rows.length + 1 // first expense row (1-based)
  for (const e of expenses) {
    rows.push([e.label, e.value])
  }
  const expEnd = rows.length // last expense row (1-based, inclusive)
  rows.push([])

  // Total expenses with SUM formula
  const totalExpRow = rows.length + 1
  rows.push([L.totalExpenses, { t: 'n', v: totalExpenses, f: `SUM(B${expStart}:B${expEnd})` }])
  rows.push([])

  // Per diem
  const perDiemRow = rows.length + 1
  rows.push([L.perDiem, perDiem])
  // Depreciation
  const depRow = rows.length + 1
  rows.push([L.depreciation, depreciation])
  rows.push([])

  // Total deductions
  const tdRow = rows.length + 1
  rows.push([L.totalDeductions, { t: 'n', v: totalDeductions, f: `B${totalExpRow}+B${perDiemRow}+B${depRow}` }])
  rows.push([])

  // Net profit
  const netRow = rows.length + 1
  rows.push([L.netProfit, { t: 'n', v: breakdown.netProfit, f: `B${incomeRow}-B${tdRow}` }])
  rows.push([])

  // SE TAX BREAKDOWN HEADER
  rows.push([L.seTaxBreakdown])

  // SE earnings = MAX(netProfit, 0) * 0.9235
  const seEarnRow = rows.length + 1
  rows.push([L.seEarnings, { t: 'n', v: breakdown.taxableSEIncome, f: `MAX(B${netRow},0)*0.9235` }])

  // SS tax = MIN(seEarnings, 184500) * 0.124
  const ssRow = rows.length + 1
  rows.push([L.ssTax, { t: 'n', v: breakdown.ssTax, f: `MIN(B${seEarnRow},184500)*0.124` }])

  // Medicare = seEarnings * 0.029
  const medRow = rows.length + 1
  rows.push([L.medicareTax, { t: 'n', v: breakdown.medicareTax, f: `B${seEarnRow}*0.029` }])

  // Additional Medicare = MAX(0, seEarnings - threshold) * 0.009
  const addMedRow = rows.length + 1
  rows.push([L.additionalMedicare, { t: 'n', v: breakdown.additionalMedicare, f: `MAX(0,B${seEarnRow}-${addlThreshold})*0.009` }])
  rows.push([])

  // Total SE tax
  const totalSeRow = rows.length + 1
  rows.push([L.totalSeTax, { t: 'n', v: breakdown.seTax, f: `B${ssRow}+B${medRow}+B${addMedRow}` }])
  rows.push([])

  // Deductible half of SE (SS + Medicare only, NOT Additional Medicare)
  const halfSeRow = rows.length + 1
  rows.push([L.deductibleHalfSE, { t: 'n', v: breakdown.deductibleHalfSE, f: `(B${ssRow}+B${medRow})/2` }])

  // AGI = netProfit - deductibleHalfSE  (if positive)
  const agiRow = rows.length + 1
  rows.push([L.agi, { t: 'n', v: breakdown.agi, f: `MAX(B${netRow}-B${halfSeRow},0)` }])

  // Standard deduction
  const stdDedRow = rows.length + 1
  rows.push([L.standardDeduction, stdDed])

  // Taxable income = MAX(0, AGI - standardDeduction)
  const taxableRow = rows.length + 1
  rows.push([L.taxableIncome, { t: 'n', v: breakdown.taxableIncome, f: `MAX(B${agiRow}-B${stdDedRow},0)` }])
  rows.push([])

  // Federal income tax — progressive bracket formula
  // Build nested IF formula over the brackets array.
  // For bracket i with cutoff C_i and rate R_i, and taxable income T:
  //   tax = sum over j where T > C_{j-1} of (MIN(T,C_j) - C_{j-1}) * R_j
  // We build a single formula:
  //  =IF(T<=0,0, SUMPRODUCT(rates, MAX(0, MIN(T-prev, cut-prev))))
  // Simpler: build nested MAX/MIN layer sum.
  const Tcell = `B${taxableRow}`
  let prev = 0
  const layerExprs = []
  for (const [cutoff, rate] of brackets) {
    layerExprs.push(`MAX(0,MIN(${Tcell},${cutoff})-${prev})*${rate}`)
    prev = cutoff
  }
  // Top bracket (above last cutoff)
  layerExprs.push(`MAX(0,${Tcell}-${prev})*${topRate}`)
  const fedFormula = layerExprs.join('+')
  const fedRow = rows.length + 1
  rows.push([L.incomeTax, { t: 'n', v: breakdown.incomeTax, f: fedFormula }])
  rows.push([])

  // Total tax = SE + Federal
  const totalTaxRow = rows.length + 1
  rows.push([L.totalTax, { t: 'n', v: breakdown.totalTax, f: `B${totalSeRow}+B${fedRow}` }])
  rows.push([])

  // Disclaimer
  rows.push([L.disclaimer])

  const ws = XLSX.utils.aoa_to_sheet(rows)
  ws['!cols'] = [{ wch: 46 }, { wch: 20 }]

  // Money format for column B
  const range = XLSX.utils.decode_range(ws['!ref'])
  for (let r = range.s.r; r <= range.e.r; r++) {
    const cell = ws[XLSX.utils.encode_cell({ r, c: 1 })]
    if (cell && typeof cell.v === 'number') {
      cell.z = '#,##0.00'
    }
  }

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Tax Summary')
  XLSX.writeFile(wb, `TruckerBook_Tax_Summary_${year}.xlsx`)
}
